async page=>{
 const origin='http://127.0.0.1:8794';await page.unrouteAll({behavior:'wait'});await page.goto(origin);
 const w=await(await page.request.get(origin+'/api/workspace')).json(),user=w.users.find(u=>u.role==='manager'),[a,b]=w.projects;w.environment='production';Object.assign(a,{execution_system:'workbench',execution_allowed:true});Object.assign(b,{execution_system:'meegle',execution_allowed:false});
 let posts=0;await page.route('**/api/**',r=>{if(r.request().method()==='GET')return r.continue();posts++;return r.fulfill({status:422,json:{detail:'validation rejected before persistence'}})});
 await page.route('**/api/session',r=>r.fulfill({json:{user,users:w.users,mode:'lark',environment:'production',workspace_id:w.workspace_id,access_mode:'normal',auth_configured:true}}));await page.route('**/api/workspace',r=>r.fulfill({json:w}));
 await page.goto(origin+`/#view=project&project=${a.id}&tab=flow`);await page.reload();const notice=page.getByRole('region',{name:'案件執行歸屬'});await notice.locator('summary').click();await notice.locator('textarea').fill('Only case A');
 await page.goto(origin+`/#view=project&project=${b.id}&tab=flow`);await page.getByRole('heading',{name:b.name,exact:true}).waitFor();await notice.locator('summary').click();const checks={};checks.crossCaseReset=await notice.locator('select').inputValue()==='meegle'&&await notice.locator('textarea').inputValue()==='';
 await notice.locator('textarea').fill('case B draft');b.execution_system='pending';b.execution_assignment={recorded_at:'new-decision'};await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await notice.getByRole('alert').waitFor();checks.remoteConflictBlocks=await notice.getByRole('button',{name:'保存歸屬核定',exact:true}).isDisabled();await notice.locator('form').evaluate(f=>f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));checks.noOldDraftSubmission=posts===0;await notice.getByRole('button',{name:'捨棄草稿並載入最新歸屬',exact:true}).click();checks.resetUsesLatest=await notice.locator('select').inputValue()==='pending'&&await notice.locator('textarea').inputValue()==='';
 const n=a.nodes[0];await page.goto(origin+`/#view=project&project=${a.id}&node=${n.id}&tab=flow&section=inputs`);const form=page.getByRole('region',{name:'作業資料登錄'});await form.waitFor();await form.getByRole('textbox',{name:'資料名稱',exact:true}).fill('validation test');const input=form.getByRole('textbox',{name:'作業資料內容',exact:true});await input.fill('中'.repeat(17000));checks.multibyteLimit=await form.getByRole('button',{name:'提交作業資料',exact:true}).isDisabled();await input.fill('valid short content');await form.getByRole('button',{name:'提交作業資料',exact:true}).click();await form.getByText('validation rejected before persistence',{exact:true}).waitFor();checks.rejected422Editable=await input.isEnabled()&&await input.inputValue()==='valid short content';checks.onlyValidationPost=posts===1;
 await page.unrouteAll({behavior:'wait'});await page.reload();if(Object.values(checks).some(v=>!v))throw Error(JSON.stringify(checks));return {fixtureOnly:true,checks};
}
