async page=>{
 const origin='http://127.0.0.1:8794';await page.unrouteAll({behavior:'wait'});await page.goto(origin);const w=await(await page.request.get(origin+'/api/workspace')).json(),p=w.projects[0],user=w.users.find(u=>u.role==='manager');w.environment='production';p.execution_system='pending';p.execution_allowed=false;p.execution_readonly_reason='待核定執行歸屬';let recovery=false,workspaceReads=0,syncs=0;
 await page.route('**/api/session',r=>r.fulfill({json:{user,users:recovery?[]:w.users,mode:'lark',environment:'production',workspace_id:w.workspace_id,access_mode:recovery?'recovery':'normal',auth_configured:true}}));await page.route('**/api/workspace',r=>{workspaceReads++;return r.fulfill({json:w})});await page.route('**/api/admin/runtime-health',r=>r.fulfill({json:{checked_at:'2026-09-29T03:00:00Z',status:'attention',worker:{status:'stale',last_success_at:null},backup:{status:'not_configured'}}}));await page.route('**/api/people/sync',r=>{syncs++;return r.fulfill({json:{status:'review_required'}})});
 const checks={};await page.goto(origin+`/#view=project&project=${p.id}&tab=files`);await page.reload();await page.getByRole('region',{name:'案件執行歸屬'}).waitFor();checks.pendingExplained=await page.getByText('待核定執行歸屬',{exact:true}).isVisible();checks.pendingUploadDisabled=await page.getByRole('button',{name:'上傳檔案',exact:true}).isDisabled();checks.assignmentEntry=await page.getByText('核定案件執行歸屬',{exact:true}).isVisible();
 p.execution_system='meegle';p.execution_readonly_reason='本案留在 Meegle 執行至完成';await page.reload();await page.getByRole('region',{name:'案件執行歸屬'}).waitFor();checks.meegleExplained=await page.getByText('本案留在 Meegle 執行至完成',{exact:true}).isVisible();checks.meegleLinkDisabled=await page.getByRole('button',{name:'加入來源連結',exact:true}).isDisabled();
 p.execution_system='workbench';p.execution_allowed=true;await page.reload();await page.getByRole('button',{name:'上傳檔案',exact:true}).waitFor();checks.workbenchUploadEnabled=await page.getByRole('button',{name:'上傳檔案',exact:true}).isEnabled();
 await page.goto(origin+'/#view=admin&tab=settings');const health=page.getByRole('region',{name:'系統維護狀態'});await health.waitFor();await health.getByText('紀錄已逾期',{exact:true}).waitFor();checks.workerStale=await health.getByText('紀錄已逾期',{exact:true}).isVisible();checks.backupNotConfigured=await health.getByText('尚未設定',{exact:true}).isVisible();checks.notIntegrationProof=await health.getByText(/不代表 Lark 各項串接或異地備份還原已驗收/).isVisible();
 recovery=true;workspaceReads=0;await page.reload();await page.getByRole('heading',{name:'公司名冊需要重新核實',exact:true}).waitFor();checks.recoveryNoWorkspace=workspaceReads===0;checks.recoveryNoCase=await page.locator('.project-title').count()===0;await page.getByRole('button',{name:'重新同步公司名冊',exact:true}).click();await page.waitForTimeout(150);checks.recoverySyncOnly=syncs===1&&workspaceReads===0;checks.recoveryLogout=await page.getByRole('button',{name:'登出',exact:true}).isVisible();
 await page.unrouteAll({behavior:'wait'});await page.reload();const failed=Object.entries(checks).filter(([,v])=>!v);if(failed.length)throw Error(JSON.stringify({checks,failed}));return {fixtureOnly:true,checks};
}
