async page=>{
 const origin='http://127.0.0.1:8794';await page.unrouteAll({behavior:'wait'});await page.goto(origin);const w=await(await page.request.get(origin+'/api/workspace')).json();w.environment='production';const p=w.projects[0],user=w.users.find(u=>u.role==='manager'),other=w.users.find(u=>u.id!==user.id);p.pm_id=user.id;p.supervisor_id=other.id;p.nodes[0].supervisor_id=other.id;
 p.evidence=[{id:'accepted-proof',status:'accepted',value:'業主書面確認',note:'可引用的業主佐證'},{id:'withdrawn-proof',status:'accepted',value:'舊資料',note:'不應列出的撤下證明',withdrawn:true},{id:'draft-proof',status:'draft',value:'未審',note:'不應列出的未審證明'}];
 const a={id:'change-lines-fixture',type:'change',project_id:p.id,node_id:p.nodes[0].id,status:'pending',title:'三線獨立fixture',reason:'測試',task_ids:[],dates:[],created_by:user.id,created_at:'2026-09-28T00:00:00+08:00',owner_confirmed:true,client_confirmed:true,lark_status:'approved',native_binding:{status:'approved',attempted:true},history:[]};w.approvals=[a];
 await page.route('**/api/session',r=>r.fulfill({json:{user,users:w.users,mode:'lark',environment:'production',workspace_id:w.workspace_id,auth_configured:true}}));await page.route('**/api/workspace',r=>r.fulfill({json:w}));let sent;
 await page.route('**/api/change-approvals/*/confirm-line',r=>{sent=r.request().postDataJSON();return r.fulfill({json:w})});
 await page.goto(origin+'/#view=approvals&approval='+a.id);await page.reload();const section=page.getByRole('region',{name:'設計變更三線確認'});await section.waitFor();const checks={};checks.legacyBoolsNotConfirmation=await section.getByText('尚未登錄本版本確認',{exact:true}).count()===2;checks.larkNotAllLines=await section.getByText('內審已核准；不代表另外兩線完成',{exact:true}).isVisible();checks.noApplyWhenOtherLinesMissing=await page.getByRole('button',{name:'手動切換新版',exact:true}).count()===0;
 await section.locator('summary').click();await section.getByRole('combobox',{name:'確認線別',exact:true}).selectOption('client');checks.noSupervisorImpersonation=await section.locator('option[value="supervisor"]').evaluate(el=>el.disabled);checks.acceptedEvidenceListed=await section.getByText('可引用的業主佐證',{exact:true}).isVisible();checks.withdrawnNotListed=await section.getByText('不應列出的撤下證明',{exact:true}).count()===0;checks.draftNotListed=await section.getByText('不應列出的未審證明',{exact:true}).count()===0;
 await section.getByRole('textbox',{name:'確認說明',exact:true}).fill('PM登錄已收到的外部業主書面確認');checks.evidenceRequired=await section.getByRole('button',{name:'保存本版本確認',exact:true}).isDisabled();await section.getByRole('checkbox').check();await section.getByRole('button',{name:'保存本版本確認',exact:true}).click();await section.getByText('已保存本版本確認紀錄；各線仍須由伺服器核實後才可套用。',{exact:true}).waitFor();checks.correctEndpointPayload=sent.party==='client'&&sent.version===w.version&&sent.evidence_ids[0]==='accepted-proof';checks.noPretendLarkApprover=!('approver_id' in sent);
 a.native_binding.attempted=false;a.status='draft';await page.reload();await section.waitFor();checks.draftCannotConfirm=await section.locator('summary').count()===0;
 await page.unrouteAll({behavior:'wait'});await page.reload();const failed=Object.entries(checks).filter(([,v])=>!v);if(failed.length)throw Error(JSON.stringify({checks,failed}));return {fixtureOnly:true,checks};
}
