async page=>{
 const origin='http://127.0.0.1:8794';await page.unrouteAll({behavior:'wait'});await page.goto(origin);const w=await(await page.request.get(origin+'/api/workspace')).json(),p=w.projects[0],user=w.users.find(u=>u.role==='manager');w.environment='production';w.settings.external_enabled=false;w.settings.drive_root='';p.files=[{id:'drive-fixture',name:'成果文件',version:1,storage:'local',direction:'output'}];let sent,count=0;
 await page.route('**/api/session',r=>r.fulfill({json:{user,users:w.users,mode:'lark',environment:'production',workspace_id:w.workspace_id,auth_configured:true}}));await page.route('**/api/workspace',r=>r.fulfill({json:w}));await page.route('**/api/files/drive-fixture/store-lark',r=>{sent=r.request().postDataJSON();count++;p.files[0].remote_status='queued';return r.fulfill({json:w})});
 await page.goto(origin+`/#view=project&project=${p.id}&tab=files`);await page.reload();const store=page.getByRole('button',{name:'保存至公司 Drive',exact:true});await store.waitFor();const checks={};checks.unconfiguredDisabled=await store.isDisabled();checks.configurationReason=await page.getByText('公司 Drive 根目錄或外部連線尚未啟用，檔案目前只在工作台暫存。',{exact:true}).isVisible();
 w.settings.external_enabled=true;w.settings.drive_root='fixture-root';await page.reload();await store.waitFor();checks.configuredOffersSave=await store.isEnabled();await store.click();await page.getByText('Drive 等待上傳',{exact:true}).waitFor();checks.versionSent=sent.version===w.version;checks.noDuplicateWhileQueued=await store.count()===0;checks.refreshReceipt=await page.getByRole('button',{name:'更新保存狀態',exact:true}).isVisible();checks.oneRequest=count===1;
 p.files[0].remote_status='outcome_unknown';await page.reload();await page.getByText('Drive 結果待核實，請勿重複上傳',{exact:true}).waitFor();checks.unknownNoResend=await store.count()===0;checks.unknownJobLink=await page.getByRole('link',{name:'查看背景工作',exact:true}).isVisible();
 p.files[0].remote_status='verified';await page.reload();await page.getByText('Drive 已上傳並讀回核實',{exact:true}).waitFor();checks.verifiedNoResend=await store.count()===0;
 await page.unrouteAll({behavior:'wait'});await page.reload();const failed=Object.entries(checks).filter(([,v])=>!v);if(failed.length)throw Error(JSON.stringify({checks,failed}));return {fixtureOnly:true,checks};
}
