async page=>{
 const origin='http://127.0.0.1:8794';await page.unrouteAll({behavior:'wait'});await page.goto(origin);const w=await(await page.request.get(origin+'/api/workspace')).json(),p=w.projects[0],n=p.nodes[0],user=w.users.find(u=>u.role==='manager');w.environment='production';p.execution_system='workbench';p.execution_allowed=true;p.pm_id=user.id;w.input_revisions=[];const submits=[];let reconciles=0,cancels=0;w.approval_connection={native_submit:{by_type:{financial:{available:false}}}};
 await page.route('**/api/session',r=>r.fulfill({json:{user,users:w.users,mode:'lark',environment:'production',workspace_id:w.workspace_id,access_mode:'normal',auth_configured:true}}));await page.route('**/api/workspace',r=>r.fulfill({json:w}));await page.route('**/api/projects/*/nodes/*/inputs',r=>{submits.push(r.request().postDataJSON());return submits.length===1?r.fulfill({status:409,json:{detail:'登錄表尚未配置'}}):r.fulfill({json:w})});await page.route('**/api/input-revisions/*/reconcile',r=>{reconciles++;return r.fulfill({json:w})});
 await page.goto(origin+`/#view=project&project=${p.id}&node=${n.id}&tab=flow&section=inputs`);await page.reload();const form=page.getByRole('region',{name:'作業資料登錄'});await form.waitFor();const checks={};checks.noTechnicalIDs=await form.getByRole('textbox').count()===2;await form.getByRole('textbox',{name:'資料名稱',exact:true}).fill('本地隔離測試');await form.getByRole('textbox',{name:'作業資料內容',exact:true}).fill('來源資料不回寫');await form.getByRole('button',{name:'提交作業資料',exact:true}).click();await form.getByText('登錄表尚未配置',{exact:true}).waitFor();checks.failedDraftRetained=await form.getByRole('textbox',{name:'作業資料內容',exact:true}).inputValue()==='來源資料不回寫';await form.getByRole('button',{name:'重試確認送交結果',exact:true}).click();await form.getByText('已交由背景工作登錄，請查看下方核實狀態。',{exact:true}).waitFor();checks.sameRequestOnRetry=submits.length===2&&submits[0].request_id===submits[1].request_id;checks.fixedHiddenKey=submits[0].key==='work_input'&&!('base_token' in submits[0]);
 w.input_revisions=[{id:'unknown-fixture',project_id:p.id,node_id:n.id,key:'work_input',label:'未知登錄',value:'保留原內容',status:'outcome_unknown'}];await page.reload();await form.getByRole('button',{name:'查回核實原登錄',exact:true}).click();await form.getByText('已查回原登錄結果，未另建立紀錄。',{exact:true}).waitFor();checks.unknownReadOnlyReconcile=reconciles===1&&submits.length===2;
 const request={id:'native-fixture',project_id:p.id,node_id:n.id,status:'draft',reason:'總開關測試',native_binding:{status:'prepared'}};w.financial_requests=[request];await page.goto(origin+`/#view=project&project=${p.id}&tab=approvals`);await page.reload();const send=page.getByRole('button',{name:'送出至 Lark',exact:true});await send.waitFor();checks.globalOffDisablesSubmit=await send.isDisabled();
 p.execution_allowed=false;p.execution_system='meegle';request.status='pending';request.native_binding={status:'outcome_unknown',attempted:true,payload:{open_id:user.id}};await page.route('**/api/native-approvals/financial/native-fixture/cancel',r=>{cancels++;request.native_binding.cancel_attempted=true;return r.fulfill({json:w})});await page.reload();const cancel=page.getByRole('button',{name:'撤回原 Lark 審批',exact:true});await cancel.waitFor();checks.readonlyKeepsOriginalPoll=await page.getByRole('button',{name:'查回原審批結果',exact:true}).isEnabled();checks.readonlyKeepsCancel=await cancel.isEnabled();await page.evaluate(()=>window.confirm=()=>true);await cancel.click();await page.getByText('已提出撤回，待 Lark 查回核實；不會再次送出撤回請求。',{exact:true}).waitFor();checks.cancelNotBlindResent=cancels===1&&await cancel.count()===0;
 await page.unrouteAll({behavior:'wait'});await page.reload();const failed=Object.entries(checks).filter(([,v])=>!v);if(failed.length)throw Error(JSON.stringify({checks,failed}));return {fixtureOnly:true,checks};
}
