async page=>{
 const origin='http://127.0.0.1:8794';await page.unrouteAll({behavior:'wait'});await page.goto(origin);const w=await(await page.request.get(origin+'/api/workspace')).json();const p=w.projects[0];const user=w.users.find(u=>u.role==='manager');w.environment='production';
 w.people_directory_status={status:'review_required',base_token:'VwAsbezz9app3YsramgjduLYp2U',table_id:'tblrXclB7LSknReZ',source_count:3,valid_people:1,last_success_at:'2026-09-28T21:22:37+08:00',issues:[{record_id:'recfixture',reason:'missing_account'},{record_id:'recduplicate',reason:'duplicate_account'}],stats:{missing_retained:1}};
 p.files=['queued','verified','outcome_unknown','simulated'].map((status,i)=>({id:'fixture'+i,file_key:'fixture'+i,name:'fixture '+status,version:1,category_id:'report',direction:'output',storage:'local',remote_status:status}));
 w.financial_requests=[{id:'fixture-finance',project_id:p.id,node_id:p.nodes[0].id,status:'draft',reason:'尚未配置原生審批'}];
 await page.route('**/api/session',r=>r.fulfill({json:{user,users:w.users,mode:'lark',environment:'production',workspace_id:w.workspace_id,auth_configured:true}}));await page.route('**/api/workspace',r=>r.fulfill({json:w}));
 await page.route('**/api/daily-reports?*',r=>r.fulfill({json:{items:[{id:'fixture-provisional',project_id:p.id,project_code:p.code,mapping_status:'provisional_case_code',date:'2026-09-28',description:'暫填案號紀錄'},{id:'fixture-unmatched',description:'未關聯紀錄'}],total:2,summary:{matched:1,unmatched:1}}}));
 const checks={};await page.goto(origin+'/#view=admin&tab=people');await page.reload();const directory=page.getByRole('region',{name:'Lark 動態人員名冊'});await directory.waitFor();
 checks.reviewRequired=await directory.getByText('名冊已讀取，部分資料待核對',{exact:true}).isVisible();await directory.locator('summary').click();
 checks.missingAccountReason=await directory.getByText('未填寫可識別的 Lark 人員帳號',{exact:false}).isVisible();checks.duplicateReason=await directory.getByText('同一人員帳號出現在多筆名冊',{exact:false}).isVisible();checks.sourceRecordLink=(await directory.getByRole('link',{name:'開啟第 1 項原始紀錄'}).getAttribute('href')).includes('record=recfixture');checks.missingRetained=await directory.getByText(/1 位既有人員已不在本次來源名冊/).isVisible();
 await page.goto(origin+`/#view=project&project=${p.id}&tab=files`);await page.locator('.file-workspace').waitFor();for(const text of ['Drive 等待上傳','Drive 已上傳並讀回核實','Drive 結果待核實，請勿重複上傳','測試模擬，未存入正式 Drive'])checks[text]=await page.getByText(text,{exact:true}).isVisible();
 await page.goto(origin+`/#view=project&project=${p.id}&tab=daily`);await page.locator('.daily-records').waitFor();await page.getByText('暫填案號紀錄',{exact:true}).waitFor();checks.provisionalExplicit=await page.getByText(/暫填工編配對，原表關聯待核對/).isVisible();checks.unmatchedExplicit=await page.getByText('待配對',{exact:true}).last().isVisible();
 await page.goto(origin+`/#view=project&project=${p.id}&tab=approvals`);await page.locator('.native-approval-controls').waitFor();checks.nativeUnconfigured=await page.getByText('尚未核實 Lark 審批單設定。',{exact:true}).isVisible();checks.noFalseSubmit=await page.getByRole('button',{name:'送出至 Lark',exact:true}).count()===0;
 await page.unrouteAll({behavior:'wait'});await page.reload();const failed=Object.entries(checks).filter(([,v])=>!v);if(failed.length)throw Error(JSON.stringify({checks,failed}));return {fixtureOnly:true,checks};
}
