import { Bell, CalendarDays, ChevronDown, ChevronRight, Loader2, Menu, Network, RefreshCw, TriangleAlert, X } from 'lucide-react';
import type { ReactNode } from 'react';
import { BarChart3, Clock3, FolderOpen, GitBranch, LayoutDashboard, ListTodo, Settings2 } from 'lucide-react';
import { DataFreshness } from './DataFreshness';
import { getSessionEpoch } from './api';
import { useDialogFocus } from './useDialogFocus';
import type { Freshness, Route, Session, User, Workspace } from './types';

export const ROLE:Record<string,string>={pm:'專案經理',manager:'系統管理員',member:'組員'};
const NAV=[{view:'dashboard',label:'工作總覽',icon:LayoutDashboard},{view:'company',label:'公司駕駛艙',icon:BarChart3},{view:'projects',label:'案件總覽',icon:FolderOpen},{view:'work',label:'我的工作',icon:ListTodo},{view:'schedule',label:'排程與人力',icon:CalendarDays},{view:'approvals',label:'變更與展延',icon:GitBranch},{view:'routines',label:'追蹤與檢討',icon:Clock3},{view:'admin',label:'管理設定',icon:Settings2}] as const;
export function Avatar({user,small=false}:{user?:User;small?:boolean}){return <span className={`avatar ${small?'small':''}`} style={{background:({'控制組':'#e8edff','圖資組':'#e8f1ed','外業組':'#fff0dd','報告組':'#f4eafa'} as Record<string,string>)[user?.department||'']}}>{(user?.name||'未').slice(-2)}</span>}
function ChevronsIcon(){return <ChevronDown size={15}/>}

type CallbackError={title:string;description:string;next:string};
export type AppShellProps={s:Session;w?:Workspace;route:Route;error:string;setError:(m:string)=>void;callbackError?:CallbackError;mobile:boolean;setMobile:(open:boolean)=>void;sessionOpen:boolean;setSessionOpen:(open:boolean)=>void;overdue:number;activeNav:string;asOfLabel:string;busy:boolean;mutationBusy:boolean;dirtyDraft:boolean;ready:boolean;go:(r:Route)=>void;refresh:()=>Promise<void>;guardedRefresh:()=>Promise<boolean>;reread:()=>void;onFreshness:(next:Freshness,snapshot?:Freshness)=>void;children:ReactNode;overlays?:ReactNode};

export function AppShell({s,w,route,error,setError,callbackError,mobile,setMobile,sessionOpen,setSessionOpen,overdue,activeNav,asOfLabel,mutationBusy,dirtyDraft,ready,go,refresh,guardedRefresh,reread,onFreshness,children,overlays}:AppShellProps){
 const navigationRef=useDialogFocus(()=>setMobile(false),mobile);
 return <div className="app-shell">
  {mobile&&<div className="sidebar-scrim" onClick={()=>setMobile(false)}/>}
  <aside ref={navigationRef} id="workspace-navigation" role={mobile?'dialog':undefined} aria-modal={mobile?true:undefined} aria-label="工作區導覽" tabIndex={-1} className={`sidebar ${mobile?'open':''}`}><button className="icon-button sidebar-close" aria-label="關閉導覽" onClick={()=>setMobile(false)}><X size={20}/></button><a className="brand" href="#view=dashboard" aria-label="詠翔工作台首頁"><span className="brand-mark"><i/><i/><i/><i/></span><span>詠翔工作台<span className="brand-en">YONG XIANG</span></span></a><div className="workspace-caption">測量工程 · 專案協作</div><div className="nav-label">工作空間</div><nav aria-label="主要導覽">{NAV.map(item=><button key={item.view} aria-current={activeNav===item.view?'page':undefined} className={`nav-item ${activeNav===item.view?'active':''}`} onClick={()=>go({view:item.view})}><item.icon size={18}/><span>{item.label}</span>{item.view==='work'&&overdue>0&&<em title="我可處理的逾期任務">逾期 {overdue}</em>}</button>)}</nav><div className="sidebar-projects"><div className="nav-label">最近案件</div>{w?.projects.filter(p=>p.case_type!=='intake').slice(0,3).map(p=><button key={p.id} className={`recent-project ${route.project===p.id?'selected':''}`} onClick={()=>go({view:'project',project:p.id})}><span className="project-dot"/><span>{p.code}<small>{p.name}</small></span></button>)}</div><div className="sidebar-bottom"><button className={`nav-item ${route.view==='sources'?'active':''}`} onClick={()=>go({view:'sources'})}><Network size={18}/><span>資料來源</span><span className="status-dot"/></button><div className="sidebar-status"><span className="tiny-dot"/>{s?.environment==='test'?'獨立測試區':s?.mode==='lark'?'公司正式區':'示範工作區'}<small>操作記錄保留於工作區</small></div><button className="user-button" onClick={()=>setSessionOpen(!sessionOpen)}><Avatar user={s?.user||undefined}/><span><strong>{s?.user?.name||'連接工作區'}</strong><small>{s?.user?ROLE[s.user.role]||s.user.department:'載入中'}</small></span><ChevronsIcon/></button></div></aside>
  <div className="main-shell"><header className="topbar"><div className="breadcrumbs"><button className="icon-button mobile-menu" onClick={()=>setMobile(!mobile)} aria-label="開啟導覽" aria-expanded={mobile} aria-controls="workspace-navigation"><Menu size={20}/></button><span>工作空間</span><ChevronRight size={13}/><strong>{route.view==='project'?'案件詳情':NAV.find(n=>n.view===route.view)?.label||'資料來源'}</strong></div><div className="topbar-right"><DataFreshness key={getSessionEpoch()} freshness={w?.freshness} onFreshness={onFreshness} demo={s.mode==='demo'} mutationActive={mutationBusy} dirtyDraft={dirtyDraft} refresh={guardedRefresh}/><span className="demo-tag">{s?.environment==='test'?'測試':s?.mode==='lark'?'正式':'DEMO'}</span><span className="top-date"><CalendarDays size={14}/>{asOfLabel}</span><button className="icon-button" title="重新整理資料" aria-label="重新整理資料" onClick={reread}><RefreshCw size={17}/></button><button className="icon-button notification-button" aria-label="查看待審申請" onClick={()=>go({view:'approvals'})}><Bell size={18}/>{(w?.scope==='shell'&&w.counts?w.counts.approvals_pending>0:w?.approvals.some(a=>a.status==='pending'))&&<i/>}</button></div></header>
  {callbackError&&<div className="error-banner auth-callback-banner" role="alert"><TriangleAlert size={18}/><span><strong>{callbackError.title}</strong><br/>{callbackError.description} {callbackError.next}</span><a className="text-button" href="/api/auth/lark/login">重新登入</a></div>}
  {error&&<div className="error-banner workspace-error" role="alert"><TriangleAlert size={18}/><span>{error}</span><button className="text-button" onClick={()=>{setError('');void refresh()}}>重新載入</button><button className="icon-button" onClick={()=>setError('')} aria-label="關閉錯誤訊息"><X size={16}/></button></div>}
  {!ready?<div className="loading-page"><span className="brand-mark"><i/><i/><i/><i/></span><h2>{error?'暫時無法連接工作區':'準備你的工作台'}</h2><p>{error?'請確認服務已啟動，或使用下方登入。':'正在讀取案件、排程與參與人員'}</p>{!error?<Loader2 className="spin"/>:<><button className="button" onClick={()=>void refresh()}>重新連接</button>{s?.auth_configured&&<a className="button primary" href="/api/auth/lark/login">使用 Lark 登入</a>}</>}</div>:<main key={route.view} className={`workspace ${route.view==='project'?'project-workspace':''}`}>
   {children}
  </main>}
  </div>
  {overlays}
 </div>
}
