import {Section,Button,Badge} from './design';
import './owned-screens.css';
import {ageFreshness,datasetNotice} from './freshness';
import {useState} from 'react';
import {api,ApiError,getSessionEpoch,liveRefresh} from './api';
import {DraftForm} from './FormDraft';
import type {Context} from './Operations';

export function AttendanceWorkSchedules({c}:{c:Context}){
 const params=new URLSearchParams(location.hash.slice(1));const today=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Taipei'});
 const[from,setFrom]=useState(today),[to,setTo]=useState(today),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const freshness=c.w.freshness?.datasets.attendance;
 const status=c.w.attendance_schedule_status;const canEdit=c.s.user?.role==='manager'||c.s.user?.capabilities?.includes('calendar_edit');const formal=c.s.mode==='lark'&&c.w.environment==='production';
 const name=(id:string)=>c.w.users.find(u=>u.id===id)?.name||'名冊待核對';
 const sync=async()=>{const epoch=getSessionEpoch();setBusy(true);setMessage('');try{const result=c.w.freshness?.enabled?await liveRefresh(['attendance'],true):await api<any>('/api/attendance/sync',{method:'POST',body:JSON.stringify({date_from:from,date_to:to})});if(epoch!==getSessionEpoch())return;if(result.freshness)c.onFreshness?.(result.freshness);await c.refresh();const state=result.freshness&&ageFreshness(result.freshness,Date.now(),Date.now()).datasets.attendance;setMessage((c.w.freshness?.enabled?state?.status==='fresh':result.status==='ready')?'已查回班表，請核對下方人員與日期。':state?datasetNotice('attendance',state)||'班表讀取結果尚未確認':'已查回同步結果，仍有條件待核對。')}catch(e){if(epoch!==getSessionEpoch())return;c.onRefreshError?.(['attendance']);if(e instanceof ApiError&&e.status===409)await c.refresh();setMessage((e as Error).message)}finally{if(epoch===getSessionEpoch())setBusy(false)}};
 const defaultUser=c.w.users.some(u=>u.id===params.get('user'))?params.get('user')||'':'';const defaultDay=/^\d{4}-\d{2}-\d{2}$/.test(params.get('day')||'')?params.get('day')||'':'';
 const reasons:Record<string,string>={employee_identity_unverified:'尚未核實 Attendance 員工識別',flexible_or_unknown_shift:'彈性班次或班次未明確，不能推算截止',missing_shift_hours:'班次缺少正常工時',ambiguous_shift_hours:'正常上下班時間有歧義',missing_or_ambiguous_schedule:'該日班表缺漏或多筆不一致'};
 const labels:Record<string,string>={ready:'本次班表查回完成',partial:'部分班表待核對',blocked:'同步條件待處理',failed:'同步失敗',pending_schedule:'班表待設定',not_configured:'尚未設定班表同步'};
 return <section className="owned-view"><h2>正常下班班表</h2><Section><p className="dataset-as-of" role="status">{c.s.mode==='demo'?'示範資料':`班表資料 as of ${freshness?.as_of?new Date(freshness.as_of).toLocaleString('zh-TW'):status?.last_success_at||'尚無讀取紀錄'}`}</p>{c.s.mode!=='demo'&&freshness&&datasetNotice('attendance',freshness)&&<p role="status">{datasetNotice('attendance',freshness)}</p>}<p>預排使用當日正常下班時間；打卡、加班不延後期限。人工已核對班表優先，缺少員工對應或班次時保持待設定。</p><div className="ops-notice"><Badge>{labels[status?.status]||'尚無核實班表同步結果'}</Badge><p>最近成功：{status?.last_success_at||'尚無'} · 最近嘗試：{status?.last_attempt_at||'尚無'}</p>{status&&<p>可用 {status.ready_count||0} 筆 · 人工優先 {status.manual_override_count||0} 筆</p>}{status?.issues?.length>0&&<ul>{status.issues.map((issue:any,index:number)=><li key={index}>{name(issue.user_id)}：{reasons[issue.reason]||'班表資料待核對'}</li>)}</ul>}</div>{canEdit&&formal&&<div className="ops-form"><h3>查回 Attendance 正常班表</h3>{!c.w.freshness?.enabled&&<div className="ops-fields"><label>起日<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>迄日<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>}{c.w.freshness?.enabled&&<p>讀取今天起十四天的正常班表。</p>}<Button variant="primary" disabled={busy||c.busy||(!c.w.freshness?.enabled&&(!from||!to||from>to))} onClick={()=>void sync()}>{busy?'查回中…':'同步正常班表'}</Button><p>只有已核實員工識別的正常班表可成為期限依據；不以打卡紀錄推算。</p></div>}{!formal&&<p>示範與測試區顯示各自的班表紀錄；公司班表請至正式工作區查看。</p>}{message&&<p role="status">{message}</p>}{canEdit&&<DraftForm key={defaultUser+defaultDay} title="補充已核對班表" draftId={`schedule-set:${defaultUser}:${defaultDay}`} busy={c.busy} onSubmit={d=>c.run('schedule_set',d)}><label>負責人<select name="user_id" defaultValue={defaultUser}><option value="">尚未指定</option>{c.w.users.filter(u=>u.active!==false).map(u=><option key={u.id} value={u.id}>{u.name} · {u.department}</option>)}</select></label><label>工作日期<input name="day" type="date" defaultValue={defaultDay} required/></label><label>正常下班時間<input name="end_time" type="time" required/></label><label>班表來源連結<input name="source_url" type="url"/></label></DraftForm>}<div className="owned-table"><table aria-label="正常下班班表" className="data-table"><thead><tr><th scope="col">人員</th><th scope="col">工作日期</th><th scope="col">正常下班</th><th scope="col">依據與狀態</th></tr></thead><tbody>{(c.w.work_schedules||[]).map((s:any,i:number)=><tr key={s.id||`${s.user_id}-${s.day}-${i}`}><td>{name(s.user_id)}</td><td>{s.day}</td><td>{s.normal_off_at?s.normal_off_at.replace('T',' '):s.end_time||'待核對'}{s.off_day_offset>0&&<small>跨日 +{s.off_day_offset} 天</small>}</td><td>{s.basis==='attendance_schedule'?'Attendance 正常班表':s.basis==='company_schedule'?'公司人工核對':s.source||'來源待核對'} · {s.active===false||s.status==='pending_schedule'?'未啟用／待核對':'已啟用'}{/^https?:\/\//i.test(s.source_url||'')&&<a href={s.source_url} target="_blank" rel="noreferrer">查看班表來源</a>}</td></tr>)}</tbody></table></div></Section></section>;
}
