import {useEffect,useState} from 'react';
import {api,ApiError} from './api';
import type {Project,Workspace} from './types';

export function AuditTrail({w,p}:{w:Workspace;p:Project}){
 const[page,setPage]=useState(0);const[data,setData]=useState<{items:any[];total:number}|null>(null);const[legacy,setLegacy]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();void api<any>(`/api/audit?project_id=${encodeURIComponent(p.id)}&offset=${page*30}&limit=30`,{signal:controller.signal}).then(result=>{if(!Array.isArray(result.items))throw new Error('操作紀錄格式不完整');setData(result);setError('');setLegacy(false)}).catch(e=>{if(controller.signal.aborted)return;if(e instanceof ApiError&&e.status===404){setLegacy(true);setError('')}else setError(e.message)});return()=>controller.abort()},[p.id,w.version,page]);
 const old=w.events.filter(e=>e.project_id===p.id);const rows=legacy?old.slice(page*30,(page+1)*30):data?.items||[];const total=legacy?old.length:data?.total||0;
 return <section className="audit-trail"><h2>操作紀錄</h2><p>查看誰在何時處理了哪些工作，以及確認、退回和來源更新的記錄。</p>{legacy&&<p className="ops-notice">目前服務僅提供舊版活動紀錄；完整變更稽核尚未接通。</p>}{error&&<p className="form-error" role="alert">{error}</p>}{rows.map((row:any,index)=><article key={row.id||index}><header><strong>{row.message||row.action}</strong><span>{row.actor_name||w.users.find(u=>u.id===row.actor_id)?.name|| (row.actor_id==='system'?'系統':'原操作人員')}</span></header><time>{row.created_at||row.at}</time>{row.reason&&<p>{row.reason}</p>}{row.outcome&&<p>結果：{row.outcome}</p>}{row.changes&&<details><summary>查看變更內容</summary><pre>{JSON.stringify(row.changes,null,2)}</pre></details>}</article>)}{!error&&!rows.length&&<p className="empty">尚無可見操作紀錄。</p>}<div className="daily-pagination"><span>共 {total} 筆</span><button className="button" disabled={!page} onClick={()=>setPage(page-1)}>上一頁</button><button className="button" disabled={(page+1)*30>=total} onClick={()=>setPage(page+1)}>下一頁</button></div></section>;
}
