import {executionAllowed} from './ProjectExecution';
import {useState} from 'react';
import {api,ApiError} from './api';
import type {Approval,Project,Session,Workspace} from './types';
import {Button} from './design';
import './NativeApproval.css';

type Context={w:Workspace;s:Session;busy:boolean;refresh:()=>Promise<void>};
export function ChangeConfirmationLines({c,p,item}:{c:Context;p:Project;item:Approval}){
 const[party,setParty]=useState<'supervisor'|'client'>(()=>c.s.user?.id===(p.nodes.find(n=>n.id===item.node_id)?.supervisor_id||p.supervisor_id)?'supervisor':'client');const[reason,setReason]=useState('');const[evidence,setEvidence]=useState<string[]>([]);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
 const a=item as Approval&{native_binding?:any;native_receipt?:any;change_confirmations?:Record<string,any>};
 const supervisor=p.nodes.find(n=>n.id===a.node_id)?.supervisor_id||p.supervisor_id;const actor=c.s.user?.id;
 const canSupervisor=!!actor&&actor===supervisor;const canClient=!!actor&&[p.pm_id,supervisor].includes(actor);
 const live=c.s.mode==='lark'&&c.w.environment==='production';const editable=live&&executionAllowed(p,c.w)&&['pending','approved'].includes(a.status)&&a.native_binding?.attempted;
 const available=(p.evidence||[]).filter((e:any)=>{if(e.status!=='accepted'||e.withdrawn)return false;if(!e.file_id)return !!String(e.value||'').trim();const file=p.files.find(f=>f.id===e.file_id);return !!file&&!file.withdrawn&&(file.storage!=='local'||file.remote_status==='verified')});
 const person=(id:string)=>c.w.users.find(u=>u.id===id)?.name||'人員待核對';
 const proof=(kind:string)=>{const record=a.change_confirmations?.[kind];return record?<><p>已登錄，套用時重新核實</p><small>{person(record.recorded_by)} · {record.recorded_at}</small><p>{record.reason}</p></>:<p>尚未登錄本版本確認</p>};
 const submit=async()=>{setBusy(true);setMessage('');try{await api(`/api/change-approvals/${encodeURIComponent(a.id)}/confirm-line`,{method:'POST',body:JSON.stringify({version:c.w.version,party,reason,evidence_ids:party==='client'?evidence:[]})});await c.refresh();setReason('');setEvidence([]);setMessage('已保存本版本確認紀錄；各線仍須由伺服器核實後才可套用。')}catch(e){if(e instanceof ApiError&&[401,409].includes(e.status))await c.refresh();setMessage((e as Error).message)}finally{setBusy(false)}};
 return <section className="change-lines" aria-label="設計變更三線確認"><div className="approval-gates glass--flat"><div><span>公司主管本人確認{proof('supervisor')}</span></div><div><span>業主確認佐證{proof('client')}</span></div><div><span>Lark 內部審批（PM＋該組主管共同核准）<p>{a.lark_status==='approved'?'內審已核准；不代表另外兩線完成':a.lark_status==='rejected'?'內審已駁回':a.native_binding?'依下方查回結果核對':'審批設定尚未核實'}</p></span></div></div><p>業主佐證由案件 PM 或指定主管登錄，不是代業主投票；內部審批由 PM 與該組主管兩位不同人共同核准，兩席不可由同一人兼任。</p>{!editable&&<p className="na-note">{live?'須先送出正式變更，才能登錄本版本確認；已結束的申請不再修改。':'隔離環境不送出正式三線確認。'}</p>}{editable&&(canSupervisor||canClient)&&<details className="na-form"><summary>登錄本版本確認</summary><form onSubmit={e=>{e.preventDefault();void submit()}}><label className="form-field">確認線別<select value={party} onChange={e=>{setParty(e.target.value as 'supervisor'|'client');setMessage('')}}><option value="supervisor" disabled={!canSupervisor}>公司主管本人確認</option><option value="client" disabled={!canClient}>登錄業主確認佐證</option></select></label>{party==='supervisor'&&!canSupervisor&&<p>此線限指定主管本人，請選擇可登錄的線別。</p>}<label className="form-field">確認說明<textarea required value={reason} onChange={e=>setReason(e.target.value)}/></label>{party==='client'&&<fieldset><legend>本案已確認的業主佐證</legend>{available.map((e:any)=><label key={e.id}><input type="checkbox" checked={evidence.includes(e.id)} onChange={event=>setEvidence(ids=>event.target.checked?[...ids,e.id]:ids.filter(id=>id!==e.id))}/>{e.note||e.value||e.key||'已确认佐證'}</label>)}{!available.length&&<p>尚無可引用佐證，請先在本案交付與確認補齊並覆核。</p>}</fieldset>}<Button variant="primary" type="submit" disabled={busy||c.busy||!reason.trim()||(party==='supervisor'?!canSupervisor:!canClient||!evidence.length)}>{busy?'保存中…':'保存本版本確認'}</Button></form></details>}{message&&<p role="status">{message}</p>}</section>;
}
