import {useEffect,useState} from 'react';
import {ArrowUpRight,RefreshCw} from 'lucide-react';
import {api} from './api';
import type {Freshness} from './types';
import {lifecycleLabel,lifecycleReasonLabel,quoteWorkflowLabel,type SourceLifecycle} from './sourceLifecycle';
import {AdmissionCell} from './ExecutionAdmission';
import {Badge,Button,Eyebrow,Row,Section,Skeleton,Stat} from './design';
import './design/skeleton.css';
import './CompanyCockpit.css';

export interface CompanyDashboard {
 as_of:string;checked_at:string;date_basis:string;source:{status:string;mapping_status:string;last_success_at:string|null};
 totals:{cases:number;confirmed_cases:number;intake_records:number;workbench_cases:number;deliveries_confirmed:number;source_status_counts:Record<string,number>;lifecycle_counts?:Record<string,number>;execution_status_counts:Record<string,number>;tasks_total:number;tasks_completed:number;tasks_overdue:number;pending_local_reviews:number;pending_native_reviews:number};
 missing:{task_due_date:number;group:number;source_status:number};
 groups:{group:string;cases:number;tasks_total:number;tasks_completed:number;tasks_overdue:number}[];
 cases:{case_type:'formal'|'intake';id:string;code:string;name:string;group:string;source_status:string;source_lifecycle?:SourceLifecycle;execution_status:string;execution_system?:string;execution_system_label?:string;execution_readonly_reason?:string|null;case_visibility?:string|null;workbench_execution_enabled?:boolean;tasks_total:number;tasks_completed:number;tasks_overdue:number;pending_local_reviews:number;pending_native_reviews:number}[];
 pagination:{offset:number;limit:number;total:number;has_more:boolean};
}
const count=(n:number)=>n.toLocaleString('zh-TW');
const time=(v:string|null)=>v&&!Number.isNaN(Date.parse(v))?new Date(v).toLocaleString('zh-TW',{hour12:false}):'尚無成功同步紀錄';
const sourceLabel=(v:string)=>({ready:'已同步',review_required:'待核對',pending:'等待同步',error:'同步異常',disabled:'尚未啟用'}[v]||'待核對');
function TableSkeleton({cases=false}:{cases?:boolean}){
 const cells=Array.from({length:cases?9:4},(_,i)=>i);
 return <div className="cockpit-table-scroll"><table className={cases?'cockpit-case-table':undefined}><thead><tr>{cells.map(i=><th key={i}><Skeleton height="var(--fs-caption)"/></th>)}</tr></thead><tbody>{[0,1,2,3].map(row=><tr key={row}>{cells.map(i=><td key={i}><Skeleton height="var(--sp-8)"/></td>)}</tr>)}</tbody></table></div>;
}
export function CompanyCockpit({refreshVersion,role,freshness}:{refreshVersion:number;role?:string|null;freshness?:Freshness}){
 const[data,setData]=useState<CompanyDashboard>();const[error,setError]=useState('');const[loading,setLoading]=useState(true);
 const[q,setQ]=useState('');const[search,setSearch]=useState('');const[group,setGroup]=useState('');const[lifecycle,setLifecycle]=useState('');const[offset,setOffset]=useState(0);const[reload,setReload]=useState(0);
 useEffect(()=>{const timer=window.setTimeout(()=>{setSearch(q.trim());setOffset(0)},250);return()=>window.clearTimeout(timer)},[q]);
 useEffect(()=>{let active=true;const controller=new AbortController();setLoading(true);setError('');const params=new URLSearchParams({offset:String(offset),limit:'40'});if(search)params.set('q',search);if(group)params.set('group',group);if(lifecycle)params.set('lifecycle',lifecycle);
  api<CompanyDashboard>(`/api/company-dashboard?${params}`,{signal:controller.signal}).then(result=>{if(active)setData(result)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'暫時無法讀取公司資料')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false;controller.abort()};
 },[search,group,lifecycle,offset,reload,refreshVersion]);
 const total=data?.totals;
 const drillDown=()=>document.getElementById('cockpit-cases-title')?.scrollIntoView({block:'start'});
 return <div className="company-cockpit" aria-busy={loading}>
  <header className="cockpit-heading"><div><Eyebrow>全公司</Eyebrow><h1>公司駕駛艙</h1><p>案件與報價紀錄、工作台交付與各組工作量。</p></div><Button className="button" disabled={loading} onClick={()=>setReload(n=>n+1)}><RefreshCw size={20} strokeWidth={1.75}/>重新整理</Button></header>
  {error&&<div className="cockpit-error" role="alert"><strong>資料暫時無法更新</strong><p>{error}</p>{data&&<p>下方保留上次成功讀取的資料，請勿視為最新狀態。</p>}<Button className="button" onClick={()=>setReload(n=>n+1)}>重試</Button></div>}
  {!data&&loading&&<><p className="cockpit-loading" role="status">正在讀取全公司案件與交付資料…</p><div className="cockpit-skeleton" aria-hidden="true">{[0,1,2,3].map(i=><div key={i} className="cockpit-skeleton-section"><Skeleton width="12rem" height="var(--fs-title2)"/>{i===0&&<><Skeleton width="60%" height="var(--fs-footnote)"/><div className="cockpit-health"><Skeleton width="5rem" height="var(--sp-9)"/><Skeleton width="12rem" height="var(--fs-footnote)"/></div></>}{i===3&&<div className="cockpit-filters">{[0,1,2].map(j=><label key={j}><Skeleton height="var(--fs-footnote)"/><Skeleton height="var(--sp-8)"/></label>)}</div>}{i<2?<div className="cockpit-skeleton-rows">{i===1&&<Skeleton width="60%" height="var(--fs-callout)"/>}<div className={i===1?'cockpit-distribution':undefined}><Skeleton lines={3} height="var(--sp-8)"/>{i===1&&<Skeleton lines={3} height="var(--sp-8)"/>}</div></div>:<TableSkeleton cases={i===3}/>}</div>)}</div></>}
  {data&&total&&<>
   <div className="cockpit-freshness" role="status"><span>{loading?'正在更新…':`資料時間 ${time(freshness?.datasets.sources.as_of&&Date.parse(freshness.datasets.sources.as_of)<Date.parse(data.checked_at)?freshness.datasets.sources.as_of:data.checked_at)}`}</span><span>來源：{data.source.status==='ready'&&data.source.mapping_status==='review_required'?'來源已讀取，部分關聯待核對':sourceLabel(data.source.status)} · 最後成功 {time(data.source.last_success_at)}</span></div>
   <div className="cockpit-overview-grid"><section className="cockpit-delivery" aria-labelledby="cockpit-delivery-title"><div className="cockpit-section-title"><h2 id="cockpit-delivery-title">工作台已確認任務</h2><span>僅計入已啟用執行的案件，不代表工程實際完成率</span></div><p className="cockpit-note">已啟用 {count(total.workbench_cases)} 件案件 · 已確認 {count(total.deliveries_confirmed)} 筆交付成果</p>{total.tasks_total===0&&total.workbench_cases===0?<Section><Row label="尚無可用的任務資料" detail="工作台尚未啟用任何案件，或來源尚未成功同步。啟用案件並完成同步後，這裡才會顯示完成與逾期數量。"/></Section>:<><div className="cockpit-health"><Stat label="已設定期限且逾期" value={count(total.tasks_overdue)} tone={total.tasks_overdue?'warning':undefined}/></div><Section><Row onClick={drillDown} label="已完成 / 全部任務" value={<>{count(total.tasks_completed)} <small>/ {count(total.tasks_total)}</small></>}/><Row onClick={drillDown} label="待本地確認" value={count(total.pending_local_reviews)}/><Row onClick={drillDown} label="待 Lark 審批" value={count(total.pending_native_reviews)}/></Section></>}{total.tasks_total>0&&<p className="cockpit-note">{data.missing.task_due_date>0?`${count(data.missing.task_due_date)} 項任務未設定期限，無法判斷是否逾期。`:'逾期判斷依已設定的任務期限。'}來源已結案不會自動視為工作台任務已完成。</p>}</section>
   <section className="cockpit-source" aria-labelledby="cockpit-source-title"><div className="cockpit-section-title"><h2 id="cockpit-source-title">案件與報價紀錄</h2><span>V4 與報價總表同步資料</span></div><Section><div className="cockpit-source-layout"><Row label="來源紀錄" value={count(total.cases)}/><div className="cockpit-source-detail"><p className="cockpit-source-summary">已成案 {count(total.confirmed_cases)} 件／待確認報價 {count(total.intake_records)} 筆</p><h3 className="cockpit-breakdown-title">案件狀態（工程進度）</h3><div className="cockpit-distribution">{Object.entries(total.lifecycle_counts||{}).sort((a,b)=>b[1]-a[1]).map(([label,n])=><Button key={label} className={lifecycle===label?'selected':''} onClick={()=>{setLifecycle(lifecycle===label?'':label);setOffset(0)}} aria-pressed={lifecycle===label}><span>{label}</span><span className="cockpit-bar" aria-hidden="true"><i style={{width:`${total.cases?n/total.cases*100:0}%`}}/></span><Badge>{count(n)}</Badge></Button>)}{!total.cases&&<p>目前沒有可顯示的來源紀錄。</p>}</div><p className="cockpit-note">案件狀態只採用來源「案件狀態」欄位的明確選項；空白、無法對應或互相衝突時顯示「待核對」，不會由日期、入帳或成案推斷結案。報價狀態與「待確認單」關聯另列，「待確認單」僅表示尚未關聯確認單。</p></div></div></Section></section>
   </div><section className="cockpit-groups" aria-labelledby="cockpit-groups-title"><div className="cockpit-section-title"><h2 id="cockpit-groups-title">各組工作量</h2><span>案件數與工作台已確認任務</span></div><Section><div className="cockpit-table-scroll"><table><thead><tr><th>組別</th><th>案件</th><th>已完成 / 任務</th><th>逾期</th></tr></thead><tbody>{data.groups.map(row=><tr key={row.group}><th scope="row"><Button variant="plain" className="cockpit-group-button" onClick={()=>{setGroup(row.group);setOffset(0)}}>{row.group||'未設定組別'}</Button></th><td>{count(row.cases)}</td><td>{count(row.tasks_completed)} / {count(row.tasks_total)}</td><td>{count(row.tasks_overdue)}</td></tr>)}</tbody></table></div></Section>{!data.groups.length&&<p className="cockpit-note">目前沒有組別工作量資料。</p>}{data.missing.group>0&&<p className="cockpit-note">{count(data.missing.group)} 件案件尚無工作台組別資料。</p>}</section>
   <section className="cockpit-cases" aria-labelledby="cockpit-cases-title"><div className="cockpit-section-title"><h2 id="cockpit-cases-title">案件與報價明細</h2><span>查閱案件與交付進度</span></div><div className="cockpit-filters"><label>搜尋案件<input type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="案件編號或名稱"/></label><label>組別<select value={group} onChange={e=>{setGroup(e.target.value);setOffset(0)}}><option value="">全部組別</option>{data.missing.group>0&&<option value="未分組">尚無工作台組別</option>}{data.groups.filter(g=>g.group).map(g=><option key={g.group} value={g.group}>{g.group}</option>)}</select></label><label>案件狀態<select value={lifecycle} onChange={e=>{setLifecycle(e.target.value);setOffset(0)}}><option value="">全部狀態</option>{Object.keys(total.lifecycle_counts||{}).map(s=><option key={s} value={s}>{s}</option>)}</select></label>{(q||group||lifecycle)&&<Button className="button" onClick={()=>{setQ('');setSearch('');setGroup('');setLifecycle('');setOffset(0)}}>清除篩選</Button>}</div>
    <Section><div className="cockpit-table-scroll"><table className="cockpit-case-table"><thead><tr><th>案件／報價</th><th>案件狀態</th><th>報價狀態</th><th>關聯</th><th>執行歸屬</th><th>組別</th><th>已完成 / 任務</th><th>逾期</th><th>待確認 / 審批</th></tr></thead><tbody>{data.cases.map(row=><tr key={row.id}><th scope="row"><a href={`#view=project&project=${encodeURIComponent(row.id)}`}><small>{row.code||'未提供編號'} · {row.case_type==='intake'?'待確認報價':'已成案'}</small><span>{row.name||'未命名案件'}<ArrowUpRight size={17} strokeWidth={1.75}/></span></a></th><td>{lifecycleLabel(row.source_lifecycle)}{!row.source_lifecycle?.canonical&&<small className="cockpit-review-required">需核對：{lifecycleReasonLabel(row.source_lifecycle)}</small>}</td><td>{quoteWorkflowLabel(row.source_lifecycle)}</td><td>{row.source_lifecycle?.relationship||(row.case_type==='intake'?'待確認單':'已關聯確認單')}</td><td><AdmissionCell p={row} role={role}/></td><td>{row.group||'未設定'}</td><td>{row.tasks_total?`${count(row.tasks_completed)} / ${count(row.tasks_total)}`:'尚無執行任務'}</td><td>{row.tasks_total?count(row.tasks_overdue):'—'}</td><td>{count(row.pending_local_reviews)} / {count(row.pending_native_reviews)}</td></tr>)}</tbody></table></div></Section>{!data.cases.length&&<p className="cockpit-empty">{total.cases?'沒有符合篩選條件的案件。':'來源同步完成後，案件會顯示於此。'}</p>}
    <footer className="cockpit-pagination"><span>共 {count(data.pagination.total)} 筆{data.cases.length?` · ${data.pagination.offset+1}–${data.pagination.offset+data.cases.length}`:''}</span><div><Button className="button" disabled={loading||offset===0} onClick={()=>setOffset(Math.max(0,offset-40))}>上一頁</Button><Button className="button" disabled={loading||!data.pagination.has_more} onClick={()=>setOffset(offset+40)}>下一頁</Button></div></footer>
   </section>
  </>}
 </div>;
}
