import {useState, type ReactNode} from 'react';
import {Activity, ArrowRight, ArrowUpRight, CalendarDays, ChevronRight, CircleCheck, Clock3, GitBranch, Play, ShieldCheck} from 'lucide-react';
import {type Project} from './types';
import {Ctx,TaskRow,active,isTaskActor,taskReadiness,openGuidedTask,allTasks,isLate,date,PageHead,Primary,openTask,nameOf,elapsed,NODE_NAMES,STATUS,progress,Empty,unmatchedDaily,num,EventList,FullWorkspaceGate} from './appCommon';

export function NextAction({c,rows}:{c:Ctx;rows:TaskRow[]}){
 const owned=rows.filter(r=>active(r.t)&&isTaskActor(r.t,c)&&r.p.case_type!=='intake');
 const ordered=[...owned].sort((a,b)=>(a.t.status==='in_progress'?-1:0)-(b.t.status==='in_progress'?-1:0)||(a.t.due_date||'9999').localeCompare(b.t.due_date||'9999'));
 const next=ordered.find(r=>!taskReadiness(r,c));const blocked=ordered.filter(r=>!!taskReadiness(r,c));
 if(!owned.length)return null;
 return <section className="next-action" aria-label="接續我的工作"><div className="next-action-heading"><span className="section-kicker">接續我的工作</span><span>{owned.length} 項待處理 · 可平行作業</span></div>{next?<><div className="next-action-main"><span className="next-action-symbol"><Play size={22}/></span><div><h2>{next.t.title}</h2><p>{next.p.code} · {next.n.name} · {next.t.status==='in_progress'?'作業中，接著補齊成果':'檢視內容後，由你確認開始'}</p></div><button className="button primary" onClick={()=>openGuidedTask(c,next)}>{next.t.status==='in_progress'?'繼續此任務':'前往此任務'}<ArrowRight size={17}/></button></div></>:<div className="next-action-main"><ShieldCheck size={24}/><div><h2>先補齊條件，再接續作業</h2><p>你負責的任務目前仍有待處理條件。</p></div></div>}{blocked.slice(0,2).map(r=><button key={r.t.id} className="next-action-blocked" onClick={()=>openGuidedTask(c,r)}><span>{r.t.title}<small>{r.p.code} · {r.n.name} · {taskReadiness(r,c)}</small></span><span>查看處理方式<ArrowRight size={14}/></span></button>)}</section>
}
export function Dashboard({c}:{c:Ctx}){
 const rows=allTasks(c.w);const overdue=rows.filter(r=>isLate(r.t,c.w.as_of));const pending=c.w.approvals.filter(a=>a.status==='pending');const dueToday=rows.filter(r=>active(r.t)&&r.t.due_date?.slice(0,10)===c.w.as_of.slice(0,10));
 const formal=c.w.projects.filter(p=>p.case_type!=='intake');const intakes=c.w.projects.filter(p=>p.case_type==='intake');
 const focus=[...formal].sort((a,b)=>b.nodes.flatMap(n=>n.tasks).filter(t=>isLate(t,c.w.as_of)).length-a.nodes.flatMap(n=>n.tasks).filter(t=>isLate(t,c.w.as_of)).length).slice(0,5);
 const tasks=[...overdue,...dueToday].slice(0,5);const reports=c.w.projects.flatMap(p=>p.daily_reports.map(r=>({...r,p}))).filter(r=>r.date===c.w.as_of.slice(0,10));
 return <div className="today-page"><PageHead eyebrow={`${date(c.w.as_of)} · 資料日期`} title="工作總覽" subtitle="先掌握待處理工作，再查看案件進度。"><button className="button" onClick={()=>c.go({view:'schedule'})}><CalendarDays size={16}/>查看排程</button><Primary onClick={()=>c.go({view:'work'})}>我的工作<ArrowRight size={16}/></Primary></PageHead>
 <div className="today-layout"><div className="today-main"><NextAction c={c} rows={rows}/><section className="work-inbox"><div className="section-heading"><div><span className="section-kicker">工作重點</span><h2>需要關注<span className="heading-count">{overdue.length+dueToday.length+pending.length}</span></h2></div><span className="section-caption">逾期 {overdue.length} · 當日到期 {dueToday.length}</span></div>
 {tasks.map(r=><button key={r.t.id} className="inbox-row" onClick={()=>openTask(c,r)}><span className={`inbox-icon ${isLate(r.t,c.w.as_of)?'late':''}`}><Clock3 size={19}/></span><span className="inbox-title"><strong>{r.t.title}</strong><small>{r.p.code} · {r.n.name} · {nameOf(c.w,r.t.owner_id)}</small></span><span className={`inbox-date ${isLate(r.t,c.w.as_of)?'late-text':''}`}>{isLate(r.t,c.w.as_of)?`逾期 ${elapsed(r.t.due_date,c.w.as_of)} 天`:'當日到期'}</span><ChevronRight size={17}/></button>)}
 {pending.slice(0,2).map(a=><button key={a.id} className="inbox-row" onClick={()=>c.go({view:'project',project:a.project_id,tab:'approvals'})}><span className="inbox-icon"><GitBranch size={19}/></span><span className="inbox-title"><strong>{a.title}</strong><small>{a.type==='change'?'設計變更':'期限展延'} · 等待確認</small></span><ChevronRight size={17}/></button>)}
 {!tasks.length&&!pending.length&&<div className="inbox-clear"><CircleCheck size={25}/><div><strong>資料日期內沒有到期或待審工作</strong><p>其他排定任務可在「我的工作」查看。</p></div></div>}
 {overdue.length+dueToday.length>5&&<button className="text-button inbox-more" onClick={()=>c.go({view:'work',tab:'all'})}>查看全部工作<ArrowRight size={15}/></button>}{pending.length>2&&<button className="text-button inbox-more" onClick={()=>c.go({view:'approvals'})}>查看全部待審申請<ArrowRight size={15}/></button>}</section>
 <section className="portfolio-preview"><div className="section-heading"><div><span className="section-kicker">正式案件</span><h2>案件進度</h2></div><button className="text-button" onClick={()=>c.go({view:'projects'})}>查看全部 {formal.length} 案<ArrowUpRight size={16}/></button></div><div className="project-preview-list">{focus.map(p=><a className="project-preview-row" key={p.id} href={`#view=project&project=${encodeURIComponent(p.id)}`}><span className="preview-identity"><small>{p.code}</small><strong>{p.name}</strong><span>{p.client}</span></span><span className="preview-stage">{p.nodes.filter(n=>['in_progress','paused'].includes(n.status)).map(n=>NODE_NAMES[n.key]||n.name).join('、')||STATUS[p.status]||p.status}</span><span className="preview-progress"><strong>{progress(p)}<small>%</small></strong><span className="progress-track"><i style={{width:`${progress(p)}%`}}/></span></span><ArrowUpRight size={17}/></a>)}{!focus.length&&<Empty title="尚無正式案件" detail="待成案資料會分開保留，確認成案後再進入此清單。"/>}</div></section></div>
 <aside className="today-aside"><section className="portfolio-totals"><span className="section-kicker">案件分流</span><a href="#view=projects&tab=formal" className="portfolio-total"><span>正式案件<small>依工程確認單建立</small></span><strong>{formal.length}<ArrowUpRight size={18}/></strong></a><a href="#view=projects&tab=intake" className="portfolio-total"><span>待確認接案<small>尚未列入正式案件</small></span><strong>{intakes.length}<ArrowUpRight size={18}/></strong></a><p>同案多筆報價集中在一個入口。</p></section>
 <section className="today-daily"><div className="section-heading"><h2>當日日報</h2><span className="heading-count">{reports.length}</span></div>{reports.slice(0,3).map(r=><button key={r.id} className="daily-row" onClick={()=>c.go({view:'project',project:r.p.id,tab:'daily'})}><span className="daily-dot"/><span><strong>{r.case_code}</strong><small>{r.department} · {r.person}</small></span><ArrowUpRight size={15}/></button>)}{!reports.length&&<p className="rail-hint">{c.s.mode==='lark'&&(c.w.source_status.status!=='ready'||unmatchedDaily(c.w)>0)?'日報來源待核對，尚無已配對紀錄':'資料日期內尚無已配對日報'}</p>}{unmatchedDaily(c.w)>0&&<div className="daily-mapping-note"><strong>{num(unmatchedDaily(c.w))} 筆日報待配對</strong><button className="text-button" onClick={()=>c.go({view:'admin',tab:'daily'})}>前往核對<ArrowRight size={14}/></button></div>}<p className="aside-footnote">填報紀錄不等同任務完成，成果仍需確認交接。</p></section>
 <section className="today-activity"><div className="section-heading"><h2>近期活動</h2><Activity size={17}/></div><EventList c={c} limit={3}/></section></aside></div></div>
}
export function ShellDashboard({c}:{c:Ctx}){
 // Built from the shell response only: counts, the server's needs-attention list and project cards. No task, node or event scan.
 const counts=c.w.counts||{approvals_pending:0,daily_unmatched:0,my_overdue_tasks:0,my_active_tasks:0};const attention=c.w.attention||[];const pending=c.w.pending_approvals||[];const overdue=counts.overdue_tasks??0,dueToday=counts.due_today_tasks??0;
 const formal=c.w.projects.filter(p=>p.case_type!=='intake');const intakes=c.w.projects.filter(p=>p.case_type==='intake');
 const focus=[...formal].sort((a,b)=>(b.overdue_tasks??0)-(a.overdue_tasks??0)).slice(0,5);const percent=(p:Project)=>p.progress?.total_nodes?Math.round(p.progress.completed_nodes/p.progress.total_nodes*100):0;
 return <div className="today-page"><PageHead eyebrow={`${date(c.w.as_of)} · 資料日期`} title="工作總覽" subtitle="先掌握待處理工作，再查看案件進度。"><button className="button" onClick={()=>c.go({view:'schedule'})}><CalendarDays size={16}/>查看排程</button><Primary onClick={()=>c.go({view:'work'})}>我的工作<ArrowRight size={16}/></Primary></PageHead>
 <div className="today-layout"><div className="today-main"><section className="work-inbox"><div className="section-heading"><div><span className="section-kicker">工作重點</span><h2>需要關注<span className="heading-count">{overdue+dueToday+counts.approvals_pending}</span></h2></div><span className="section-caption">逾期 {overdue} · 當日到期 {dueToday}</span></div>
 {attention.slice(0,5).map(a=><button key={a.task_id} className="inbox-row" onClick={()=>c.go({view:'project',project:a.project_id,node:a.node_id,task:a.task_id,tab:'flow'})}><span className={`inbox-icon ${a.due_date.slice(0,10)<c.w.as_of.slice(0,10)?'late':''}`}><Clock3 size={19}/></span><span className="inbox-title"><strong>{a.title||'未命名任務'}</strong><small>{a.project_code} · {a.node_name||NODE_NAMES[a.node_key]||a.node_key} · {nameOf(c.w,a.assignee_id)}</small></span><span className={`inbox-date ${a.due_date.slice(0,10)<c.w.as_of.slice(0,10)?'late-text':''}`}>{a.due_date.slice(0,10)<c.w.as_of.slice(0,10)?`逾期 ${elapsed(a.due_date,c.w.as_of)} 天`:'當日到期'}</span><ChevronRight size={17}/></button>)}
 {pending.map(a=><button key={a.id} className="inbox-row" onClick={()=>c.go({view:'project',project:a.project_id,tab:'approvals'})}><span className="inbox-icon"><GitBranch size={19}/></span><span className="inbox-title"><strong>{a.title}</strong><small>{a.type==='change'?'設計變更':'期限展延'} · 等待確認</small></span><ChevronRight size={17}/></button>)}
 {counts.approvals_pending>pending.length&&<button className="text-button inbox-more" onClick={()=>c.go({view:'approvals'})}>查看全部待審申請<ArrowRight size={15}/></button>}
 {!attention.length&&!counts.approvals_pending&&<div className="inbox-clear"><CircleCheck size={25}/><div><strong>資料日期內沒有到期或待審工作</strong><p>其他排定任務可在「我的工作」查看。</p></div></div>}
 {overdue+dueToday>attention.slice(0,5).length&&<button className="text-button inbox-more" onClick={()=>c.go({view:'work',tab:'all'})}>查看全部工作<ArrowRight size={15}/></button>}</section>
 <section className="portfolio-preview"><div className="section-heading"><div><span className="section-kicker">正式案件</span><h2>案件進度</h2></div><button className="text-button" onClick={()=>c.go({view:'projects'})}>查看全部 {formal.length} 案<ArrowUpRight size={16}/></button></div><div className="project-preview-list">{focus.map(p=><a className="project-preview-row" key={p.id} href={`#view=project&project=${encodeURIComponent(p.id)}`}><span className="preview-identity"><small>{p.code}</small><strong>{p.name}</strong><span>{p.client}</span></span><span className="preview-stage">{STATUS[p.execution_status||p.status]||p.status}</span><span className="preview-progress"><strong>{percent(p)}<small>%</small></strong><span className="progress-track"><i style={{width:`${percent(p)}%`}}/></span></span><ArrowUpRight size={17}/></a>)}{!focus.length&&<Empty title="尚無正式案件" detail="待成案資料會分開保留，確認成案後再進入此清單。"/>}</div></section></div>
 <aside className="today-aside"><section className="portfolio-totals"><span className="section-kicker">案件分流</span><a href="#view=projects&tab=formal" className="portfolio-total"><span>正式案件<small>依工程確認單建立</small></span><strong>{formal.length}<ArrowUpRight size={18}/></strong></a><a href="#view=projects&tab=intake" className="portfolio-total"><span>待確認接案<small>尚未列入正式案件</small></span><strong>{intakes.length}<ArrowUpRight size={18}/></strong></a><p>同案多筆報價集中在一個入口。</p></section>
 <section className="today-daily"><div className="section-heading"><h2>當日日報</h2></div>{unmatchedDaily(c.w)>0?<div className="daily-mapping-note"><strong>{num(unmatchedDaily(c.w))} 筆日報待配對</strong><button className="text-button" onClick={()=>c.go({view:'admin',tab:'daily'})}>前往核對<ArrowRight size={14}/></button></div>:<p className="rail-hint">日報請至各案件的「日報」頁查看</p>}<p className="aside-footnote">填報紀錄不等同任務完成，成果仍需確認交接。</p></section>
 <ShellActivity c={c}/></aside></div></div>
}
export function ShellActivity({c}:{c:Ctx}){
 const[open,setOpen]=useState(false);
 return <section className="today-activity"><div className="section-heading"><h2>近期活動</h2><Activity size={17}/></div>{open?<FullWorkspaceGate c={c}>{fc=><EventList c={fc} limit={3}/>}</FullWorkspaceGate>:<button className="text-button" onClick={()=>setOpen(true)}>載入近期活動</button>}</section>
}
export function Metric({label,value,detail,icon,warn=false,onClick}:{label:string;value:number;detail:string;icon:ReactNode;warn?:boolean;onClick?:()=>void}){return <button className={`metric ${warn?'warning':''}`} onClick={onClick} disabled={!onClick}><span className="metric-label">{label}{icon}</span><strong>{value.toString().padStart(2,'0')}</strong><small>{detail}</small></button>}
