import {useEffect,useMemo,useRef,useState} from 'react';
import {api,ApiError} from './api';
import {dailyReviewLabel} from './dailyReview';
import type {Project,Route,Workspace} from './types';
import {Button,Skeleton} from './design';
import './DailyRecords.css';

export function DailyRecords({w,p,go}:{w:Workspace;p:Project;go:(r:Route)=>void}){
 const[scope,setScope]=useState('project');const[query,setQuery]=useState('');const[day,setDay]=useState('');const[pg,setPg]=useState({pid:p.id,n:0});if(pg.pid!==p.id)setPg({pid:p.id,n:0});const page=pg.pid===p.id?pg.n:0;const setPage=(n:number)=>setPg({pid:p.id,n});
 const[remote,setRemote]=useState<{key:string;items:any[];total:number;summary:Record<string,number>;last_sync?:string}|null>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(false);const[fallback,setFallback]=useState(false);
 const requestKey=useMemo(()=>{const params=new URLSearchParams({offset:String(page*30),limit:'30',status:scope==='unmatched'?'unmatched':'all'});if(scope==='project')params.set('project_id',p.id);if(query)params.set('q',query);if(day){params.set('date_from',day);params.set('date_to',day)}return params.toString()},[scope,query,day,page,p.id]);
 const seq=useRef(0);const[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();const gen=++seq.current;const live=()=>gen===seq.current&&!controller.signal.aborted;setLoading(true);setRemote(null);setFallback(false);setError('');
  void api<any>('/api/daily-reports?'+requestKey,{signal:controller.signal}).then(result=>{if(!live())return;if(!Array.isArray(result.items)||typeof result.total!=='number')throw new Error('日報回應格式不完整');setRemote({...result,key:requestKey});setFallback(false);setError('')}).catch(e=>{if(!live())return;if(e instanceof ApiError&&e.status===404){setFallback(true);setRemote(null);setError('')}else setError(e.message)}).finally(()=>{if(live())setLoading(false)});return()=>{seq.current++;controller.abort()};
 },[requestKey,w.version,retry]);
 const current=remote&&remote.key===requestKey?remote:null;
 const remotePageCount=current?Math.max(1,Math.ceil(current.total/30)):1;
 const pageOutOfRange=!!current&&page>=remotePageCount;
 const records=useMemo(()=>{
  const matched=w.projects.flatMap(project=>(project.daily_reports||[]).map(row=>({...row,project,unmatched:false})));
  const unmatched=(w.daily_unmatched||[]).map((row:any)=>({...row,project:null,unmatched:true}));
  return [...matched,...unmatched];
 },[w]);
 const filtered=records.filter(r=>(scope==='all'||scope==='unmatched'&&r.unmatched||scope==='project'&&r.project?.id===p.id)&&(!day||r.date?.slice(0,10)===day)&&`${r.person||''} ${r.department||''} ${r.description||''} ${r.project?.code||r.source_case_code||r.case_code||''}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));
 const total=current?.total??(fallback?filtered.length:0);const settled=!!current||fallback;const currentPage=settled?Math.min(page,Math.max(1,Math.ceil(total/30))-1):page;const pageCount=Math.max(1,Math.ceil(total/30),currentPage+1);const visible:any[]=current&&!pageOutOfRange?current.items.map(r=>({...r,unmatched:!r.project_id,project:r.project_id?{id:r.project_id,code:r.project_code}:null})):fallback?filtered.slice(currentPage*30,(currentPage+1)*30):[];
 useEffect(()=>{if(settled&&page!==currentPage)setPage(currentPage)},[settled,page,currentPage,p.id]);
 return <section className="daily-records"><header className="dr-head"><h2>日報紀錄</h2><p>原表唯讀。日報檢核在 Lark 處理，日報存在不代表成果交付完成。</p></header><div className="daily-filters" data-reload-safe><label>查看範圍<select value={scope} onChange={e=>{setScope(e.target.value);setPage(0)}}><option value="project">本案已配對</option><option value="all">全部可見日報</option><option value="unmatched">待配對</option></select></label><label>搜尋人員、內容或案號<input value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}}/></label><label>作業日期<input type="date" value={day} onChange={e=>{setDay(e.target.value);setPage(0)}}/></label></div>{(records.some(r=>r.unmatched)||Number(current?.summary?.unmatched)>0)&&<div className="dr-note ops-notice">待配對資料尚未歸屬案件，不計入本案成果。<Button variant="plain" onClick={()=>go({view:'admin',tab:'daily'})}>前往配對核對</Button></div>}{error&&<p className="dr-note ops-notice" data-tone="critical" role="alert">{error} <Button onClick={()=>setRetry(n=>n+1)}>重試日報</Button></p>}{fallback&&<p className="dr-note ops-notice">目前服務尚未提供全量日報查詢，下方僅列工作區已載入紀錄。</p>}<p role="status">{error?"日報讀取失敗，筆數尚未確認":loading||pageOutOfRange||!settled?"正在讀取日報…":`共 ${total} 筆符合條件 · 第 ${currentPage+1}／${pageCount} 頁`}</p>{loading&&!visible.length&&<Skeleton lines={3} height="5rem"/>}<div className="daily-cards ds-group glass--flat">{visible.map((r,i)=><article key={`${r.project?.id||'unmatched'}:${r.id||i}`}><header><strong>{r.date||'日期待核對'} · {r.department||'組別待核對'}</strong><span>{r.person||'人員待核對'}</span></header><p>{r.description||'來源未填寫作業內容'}</p><footer><span>{r.unmatched?'待配對':r.project?.code}{!r.unmatched&&(r.match_basis==='provisional_case_code'||r.mapping_status==='provisional_case_code')&&' · 暫填工編配對，原表關聯待核對'}{r.source_case_code&&r.unmatched&&` · 來源案號 ${r.source_case_code}`}</span><span>{dailyReviewLabel(r.review)}</span>{/^https?:\/\//i.test(r.source_url||'')&&<a href={r.source_url} target="_blank" rel="noreferrer">開啟 Lark 原日報</a>}</footer></article>)}</div>{!loading&&!pageOutOfRange&&!error&&!total&&<p className="dr-empty">{scope==='unmatched'?'此篩選條件下尚無待配對紀錄。':'此範圍尚無已配對紀錄；不代表確定未作業。'}</p>}<div className="daily-pagination"><Button disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}>上一頁</Button><Button disabled={currentPage+1>=pageCount} onClick={()=>setPage(currentPage+1)}>下一頁</Button></div></section>;
}
