import {executionAllowed} from './ProjectExecution';
import {useMemo,useState,type FormEvent} from 'react';
import {Badge,Button,Row,Section} from './design';
import './file-workspace.css';
import {DriveFileStorage} from './DriveFileStorage';
import {useDialogFocus} from './useDialogFocus';
import type {Project,Node,Workspace,Session} from './types';

type Context={w:Workspace;s:Session;busy:boolean;error:string;refresh:()=>Promise<void>;run:(action:string,payload?:Record<string,unknown>,scope?:{project_id?:string;node_id?:string;task_id?:string})=>Promise<Workspace|undefined>;upload:(data:FormData)=>Promise<boolean>};
type Category={id:string;name?:string;label?:string;active?:boolean;order?:number};
const defaults:Category[]=[{id:'quote_confirmation',name:'報價／確認單'},{id:'field_raw',name:'外業原始資料'},{id:'photo',name:'照片'},{id:'drawing',name:'圖資圖面'},{id:'report',name:'成果報告'},{id:'evidence',name:'交付佐證'},{id:'other',name:'其他'}];
const categories=(w:Workspace):Category[]=>w.file_categories?.length?w.file_categories:defaults;
const safe=(url:string)=>/^https?:\/\//i.test(url||'');
const driveStatus:Record<string,string>={queued:'Drive 等待上傳',running:'Drive 正在上傳／核實',verified:'Drive 已上傳並讀回核實',simulated:'測試模擬，未存入正式 Drive',blocked:'Drive 保存受阻，待處理',failed:'Drive 保存失敗，待處理',outcome_unknown:'Drive 結果待核實，請勿重複上傳',retry:'Drive 等待重試'};
const directions:Record<string,string>={input:'作業資料',output:'作業成果',evidence:'交付佐證'};

export function FilePanel({c,p,node}:{c:Context;p:Project;node?:Node}){
 const[category,setCategory]=useState('all');const[direction,setDirection]=useState('all');const[scope,setScope]=useState('all');const[modal,setModal]=useState('');
 const catalog=categories(c.w);const categoryName=(id:string)=>catalog.find(x=>x.id===id)?.name||catalog.find(x=>x.id===id)?.label||'其他';
 const filtered=p.files.filter(f=>(category==='all'||(f.category_id||'other')===category)&&(direction==='all'||f.direction===direction)&&(scope==='all'||f.node_id===scope));
 const groups=useMemo(()=>{const result=new Map<string,typeof filtered>();for(const f of filtered){const key=f.file_key||f.id;result.set(key,[...(result.get(key)||[]),f])}return [...result.values()].map(group=>group.sort((a,b)=>Number(b.version)-Number(a.version)))},[filtered]);
 return <section className="file-workspace file-screen"><div className="section-heading"><div><h2>作業資料與成果</h2><p>檔案類別、所屬階段與用途分開記錄；同一檔案的版本集中留存。</p></div><div className="heading-actions"><Button disabled={!executionAllowed(p,c.w)} onClick={()=>setModal('link')}>加入來源連結</Button><Button variant="primary" disabled={!executionAllowed(p,c.w)} onClick={()=>setModal('upload')}>上傳檔案</Button></div></div><div className="daily-filters"><label>檔案類別<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">所有類別</option>{catalog.map(cat=><option key={cat.id} value={cat.id}>{cat.name||cat.label}{cat.active===false?'（停用）':''}</option>)}</select></label><label>用途<select value={direction} onChange={e=>setDirection(e.target.value)}><option value="all">所有用途</option>{Object.entries(directions).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>所屬階段<select value={scope} onChange={e=>setScope(e.target.value)}><option value="all">所有階段</option><option value="">案件共用</option>{p.nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label></div><p>{filtered.length} 筆版本 · {groups.length} 組檔案</p><div className="file-groups">{groups.map(group=><Section key={group[0].file_key||group[0].id}><Row label={<strong>{group[0].name}</strong>} detail={<>{categoryName(group[0].category_id||'other')} · {directions[group[0].direction]||'用途待核對'}</>}/>{group.map((f,index)=><div className="file-version" key={f.id}><Badge>v{f.version}{index===0?' · 最新':''}{f.withdrawn?' · 已撤下':''}</Badge><small>{p.nodes.find(n=>n.id===f.node_id)?.name||'案件共用'} · {f.created_at?.slice(0,10)} · {c.w.users.find(u=>u.id===f.uploaded_by)?.name||'來源人員'}</small><small className="file-storage-status">{f.storage==='link'?'來源連結，未另存 Drive':driveStatus[f.remote_status]||'工作台暫存，尚未核實 Drive 保存'}</small>{safe(f.remote_url)&&<a href={f.remote_url} target="_blank" rel="noreferrer">開啟 Drive 原檔</a>}<DriveFileStorage c={c} p={p} file={f}/>{!f.withdrawn&&(f.storage==='link'?safe(f.url)&&<a href={f.url} target="_blank" rel="noreferrer">開啟來源</a>:<a href={`/api/files/${encodeURIComponent(f.id)}/download`}>下載此版本</a>)}</div>)}</Section>)}</div>{!filtered.length&&<p className="empty">此範圍尚無檔案，可上傳作業資料或引用來源連結。</p>}{!!p.source_attachments?.length&&<Section title="Lark 來源附件索引"><div className="source-attachment-index"><p>此處只顯示來源附件資訊，未代表已下載或存入工作台。</p>{p.source_attachments.map((f:any)=><article key={f.id}><strong>{f.name||'來源附件'}</strong><span>{f.status==='source_missing'?'來源已移除，保留索引':'來源附件'} · {f.source_field}</span>{safe(f.source_url)&&<a href={f.source_url} target="_blank" rel="noreferrer">開啟 Lark 原紀錄</a>}</article>)}</div></Section>}{modal&&<FileModal c={c} p={p} node={node} mode={modal} onClose={()=>setModal('')}/>}</section>;
}

export function FileModal({c,p,node,mode,onClose,defaultDirection='input'}:{c:Context;p:Project;node?:Node;mode:string;onClose:()=>void;defaultDirection?:'input'|'output'|'evidence'}){
 const ref=useDialogFocus(()=>close());const[error,setError]=useState('');const[hasInput,setHasInput]=useState(false);const[versionKey,setVersionKey]=useState('');
 const catalog=categories(c.w).filter(x=>x.active!==false);const suggested=({field:'field_raw',mapping:'drawing',report:'report',confirmation:'quote_confirmation'} as Record<string,string>)[node?.key||'']||'other';
 const groups=[...new Map(p.files.filter(f=>!f.withdrawn).map(f=>[f.file_key||f.id,{...f,file_key:f.file_key||f.id}])).values()];
 const chooseVersion=(select:HTMLSelectElement)=>{setVersionKey(select.value);const previous=groups.find(f=>f.file_key===select.value);if(previous&&select.form){for(const[name,value]of Object.entries({category_id:(previous as any).category_id||'other',node_id:previous.node_id||'',direction:previous.direction})){const field=select.form.elements.namedItem(name);if(field instanceof HTMLSelectElement)field.value=value}}};
 const close=()=>{if(!hasInput||window.confirm('尚未上傳或儲存的檔案資料會捨棄，確定關閉？'))onClose()};
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setError('');const data=new FormData(event.currentTarget);data.set('project_id',p.id);if(mode==='upload'){const file=data.get('file');if(!(file instanceof File)||!file.size){setError('請選擇檔案');return}if(await c.upload(data))onClose()}else if(await c.run('file_link',{name:data.get('name'),url:data.get('url'),direction:data.get('direction'),category_id:data.get('category_id'),file_key:data.get('file_key'),version:Number(data.get('file_version')||1)},{project_id:p.id,node_id:String(data.get('node_id')||'')}))onClose()};
 return <div className="ds-backdrop file-sheet-backdrop"><section ref={ref} tabIndex={-1} className="ds-sheet glass file-sheet" role="dialog" aria-modal="true" aria-label={mode==='upload'?'上傳作業檔案':'加入來源連結'}><header><div><h2>{mode==='upload'?'上傳作業檔案':'加入來源連結'}</h2><p>先分類，再選擇所屬階段及用途。</p></div><Button variant="plain" aria-label="關閉檔案表單" onClick={close}>×</Button></header><form onSubmit={e=>void submit(e)} onChange={()=>setHasInput(true)}><div className="file-sheet-body"><label className="form-field">檔案類別<select name="category_id" defaultValue={catalog.some(x=>x.id===suggested)?suggested:'other'}>{catalog.map(cat=><option key={cat.id} value={cat.id}>{cat.name||cat.label}</option>)}</select></label><div className="form-row"><label className="form-field">所屬階段<select name="node_id" defaultValue={node?.id||''}><option value="">案件共用</option>{p.nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><label className="form-field">用途<select name="direction" defaultValue={defaultDirection}>{Object.entries(directions).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><label className="form-field">版本歸屬<select name="file_key" value={versionKey} onChange={e=>chooseVersion(e.target)}><option value="">新增一組檔案</option>{groups.map(f=><option key={f.file_key} value={f.file_key}>{f.name} · 上傳新版</option>)}</select></label>{mode==='upload'?<label className="form-field">選擇檔案<input type="file" name="file" required/></label>:<><label className="form-field">文件名稱<input name="name" required/></label><label className="form-field">來源網址<input name="url" type="url" required placeholder="https://…"/></label><input type="hidden" name="file_version" value={versionKey?Math.max(...p.files.filter(f=>(f.file_key||f.id)===versionKey).map(f=>Number(f.version)))+1:1}/></>}<p>上傳後會自動安排 Drive 保存；保存與讀回結果會另行顯示，尚未核實前不代表已存入 Drive。來源連結的閱讀權限由原系統管理。</p>{(error||c.error)&&<p className="form-error" role="alert">{error||c.error}</p>}</div><footer><Button type="button" onClick={close}>取消</Button><Button variant="primary" disabled={c.busy} type="submit">{c.busy?'處理中…':mode==='upload'?'上傳檔案':'儲存連結'}</Button></footer></form></section></div>;
}
