import {createContext,useContext,useEffect,useRef,useState,type FormEvent,type ReactNode} from 'react';

export const DraftNamespace=createContext('');
type Saved=Record<string,string[]>;
export function DraftForm({title,draftId='',onSubmit,children,busy}:{title:string;draftId?:string;onSubmit:(values:Record<string,FormDataEntryValue>,e:FormEvent<HTMLFormElement>)=>void|Promise<unknown>;children:ReactNode;busy:boolean}){
 const namespace=useContext(DraftNamespace);const params=new URLSearchParams(location.hash.slice(1));
 const key=`yx:draft:v2:${namespace}:form:${params.get('project')||''}:${params.get('node')||''}:${draftId||title}`;
 const ref=useRef<HTMLFormElement>(null);const [stored,setStored]=useState<Saved|null>(()=>{try{const entry=JSON.parse(sessionStorage.getItem(key)||'null');return entry&&Date.now()-entry.at<86400000?entry.value:null}catch{return null}});const[notice,setNotice]=useState(stored?'有未送出的暫存文字，可核對後恢復。':'');
 useEffect(()=>{try{const entry=JSON.parse(sessionStorage.getItem(key)||'null');const next=entry&&Date.now()-entry.at<86400000?entry.value:null;setStored(next);setNotice(next?'有未送出的暫存文字，可核對後恢復。':'')}catch{setStored(null);setNotice('')}},[key]);
 const capture=()=>{if(!namespace||!ref.current)return;const values:Saved={};for(const element of Array.from(ref.current.elements)){if(!(element instanceof HTMLInputElement||element instanceof HTMLTextAreaElement||element instanceof HTMLSelectElement)||!element.name||['password','file','hidden'].includes(element.type))continue;values[element.name]??=[];if(element instanceof HTMLInputElement&&['checkbox','radio'].includes(element.type)){if(element.checked)values[element.name].push(element.value)}else values[element.name].push(element.value)}try{sessionStorage.setItem(key,JSON.stringify({value:values,at:Date.now()}));setStored(values)}catch{setNotice('瀏覽器無法暫存，請勿關閉此頁。')}};
 const restore=()=>{if(!ref.current||!stored)return;for(const element of Array.from(ref.current.elements)){if(!(element instanceof HTMLInputElement||element instanceof HTMLTextAreaElement||element instanceof HTMLSelectElement)||!(element.name in stored)||['password','file','hidden'].includes(element.type))continue;const values=stored[element.name];if(element instanceof HTMLInputElement&&['checkbox','radio'].includes(element.type)){Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'checked')?.set?.call(element,values.includes(element.value))}else{const prototype=element instanceof HTMLInputElement?HTMLInputElement.prototype:element instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLSelectElement.prototype;Object.getOwnPropertyDescriptor(prototype,'value')?.set?.call(element,values[0]||'')}element.dispatchEvent(new Event('input',{bubbles:true}));element.dispatchEvent(new Event('change',{bubbles:true}))}setNotice('已恢復文字，請核對目前人員、版本與排程後再儲存。檔案需重新選擇。')};
 return <details className="ops-form"><summary>{title}</summary>{stored&&<div className="draft-recovery"><p>{notice||'文字已暫存於本分頁，尚未送出。'}</p><button className="button" type="button" onClick={restore}>恢復暫存文字</button><button className="text-button" type="button" onClick={()=>{sessionStorage.removeItem(key);setStored(null);setNotice('')}}>捨棄暫存</button></div>}<form ref={ref} onChange={capture} onSubmit={e=>{e.preventDefault();capture();const result=onSubmit(Object.fromEntries(new FormData(e.currentTarget).entries()),e);if(result&&typeof (result as Promise<unknown>).then==='function')void Promise.resolve(result).then(saved=>{if(!saved)return;sessionStorage.removeItem(key);setStored(null);setNotice('')}).catch(()=>{})}}><div className="ops-fields">{children}</div><button className="button primary" disabled={busy} type="submit">儲存</button></form></details>;
}
