import {useEffect,useState} from 'react';
import {api,ApiError} from './api';
import {draftKey,useDraft} from './drafts';
import {executionAllowed} from './ProjectExecution';
import {classifyFailure,disposalReady,draftAfterFailure,freshDraft,needsRefresh,persistedFor,timeoutInit,DISPOSAL_REASON_MAX} from './inputRecovery';
import type {Node,Project,Session,Workspace} from './types';
type Context={w:Workspace;s:Session;busy:boolean;refresh:()=>Promise<void>};
export function InputRegistration({c,p,n,canSubmit}:{c:Context;p:Project;n:Node;canSubmit:boolean}){
 const[draft,setDraft]=useDraft(draftKey(c.s,c.w,`input-registration:${p.id}:${n.id}`),freshDraft());const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[disposing,setDisposing]=useState('');const[confirmed,setConfirmed]=useState(false);const[reason,setReason]=useState('');
 const enabled=c.s.mode==='lark'&&(c.w.environment==='production'||(c.w.environment==='test'&&c.w.settings.test_connection_mode==='isolated_live'))&&executionAllowed(p,c.w)&&canSubmit;
 const rows=(c.w.input_revisions||[]).filter((r:any)=>r.project_id===p.id&&r.node_id===n.id&&r.key==='work_input');
 const labels:Record<string,string>={queued:'等待登錄',running:'登錄中',succeeded:'已登錄並核實',outcome_unknown:'結果待核實',blocked:'登錄受阻',failed:'登錄失敗',simulated:'模擬登錄',not_created:'已確認未建立並處置'};
 const oversized=new TextEncoder().encode(JSON.stringify(draft.value)).length>50000;
 useEffect(()=>{if(persistedFor(rows,draft.request_id)){setDraft(freshDraft());setMessage('先前的提交已建立紀錄，請查看下方核實狀態；未重複送出。')}},[rows.map((r:any)=>r.request_id).join(',')]);
 const submit=async()=>{if(oversized){setMessage('Input 內容超過 50KB，請縮短內容或使用文件交付');return}const wasAttempted=draft.attempted;const sent=draft;setBusy(true);setMessage('');setDraft(d=>({...d,attempted:true}));const t=timeoutInit();try{await api(`/api/projects/${encodeURIComponent(p.id)}/nodes/${encodeURIComponent(n.id)}/inputs`,{method:'POST',signal:t.signal,body:JSON.stringify({version:c.w.version,project_version:p.concurrency_version,request_id:sent.request_id,key:'work_input',label:sent.label,value:sent.value})});t.done();await c.refresh();setDraft(freshDraft());setMessage('已交由背景工作登錄，請查看下方核實狀態。')}catch(e){t.done();const kind=classifyFailure(e);setDraft(d=>draftAfterFailure(d,kind,wasAttempted));if(needsRefresh(kind))await c.refresh().catch(()=>{});setMessage(kind==='unknown'?'送出結果尚未確認；已保留原提交識別與內容，請按「重試確認送交結果」，不會重複登錄。':(e as Error).message)}finally{setBusy(false)}};
 const reconcile=async(id:string)=>{setBusy(true);setMessage('');try{await api(`/api/input-revisions/${encodeURIComponent(id)}/reconcile`,{method:'POST',body:JSON.stringify({version:c.w.version,project_version:p.concurrency_version})});await c.refresh();setMessage('已查回原登錄結果，未另建立紀錄。')}catch(e){if(e instanceof ApiError&&[401,409].includes(e.status))await c.refresh();setMessage((e as Error).message)}finally{setBusy(false)}};
 const dispose=async(id:string)=>{setBusy(true);setMessage('');try{await api(`/api/input-revisions/${encodeURIComponent(id)}/dispose-not-created`,{method:'POST',body:JSON.stringify({version:c.w.version,project_version:p.concurrency_version,confirm_not_created:true,reason:reason.trim()})});await c.refresh();setDisposing('');setConfirmed(false);setReason('');setMessage('已記錄「確認未建立」處置；可重新提交。')}catch(e){if(e instanceof ApiError&&[401,409].includes(e.status))await c.refresh().catch(()=>{});setMessage((e as Error).message)}finally{setBusy(false)}};
 const clearDraft=()=>{setDraft(freshDraft());setMessage('已清除未送出的草稿，可以重新填寫。')};
 return <section aria-label="作業資料登錄"><h3>作業資料登錄</h3><p>交付資料會保留版本與提交人，並在下方顯示登錄狀態。</p>{enabled&&<form className="ops-form" onSubmit={e=>{e.preventDefault();void submit()}}><label className="form-field">資料名稱<input required maxLength={200} disabled={draft.attempted} value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})}/></label><label className="form-field">作業資料內容<textarea required maxLength={20000} disabled={draft.attempted} value={draft.value} onChange={e=>setDraft({...draft,value:e.target.value})}/></label>{oversized&&<p role="alert">內容超過 50KB，請縮短內容或使用文件交付。</p>}{draft.attempted&&<p>保留原提交識別與內容，重試只查核同一次提交，避免重複登錄。</p>}<button className="button" disabled={busy||c.busy||oversized||!draft.label.trim()||!draft.value.trim()}>{busy?'處理中…':draft.attempted?'重試確認送交結果':'提交作業資料'}</button>{!draft.attempted&&(draft.label||draft.value)&&<button type="button" className="button" disabled={busy||c.busy} onClick={clearDraft}>清除草稿重新填寫</button>}</form>}{rows.map((r:any)=><article className="ops-input" key={r.id}><strong>{r.label}</strong><p>{typeof r.value==='string'?r.value:'已保存結構化資料'}</p><p>{labels[r.status]||'狀態待核對'} · {r.created_at}</p>{enabled&&r.status==='outcome_unknown'&&<button className="button compact" disabled={busy||c.busy} onClick={()=>void reconcile(r.id)}>查回核實原登錄</button>}{enabled&&r.status==='outcome_unknown'&&(disposing===r.id?<div className="ops-form"><p>僅在查回仍找不到、且已向遠端核對確實未建立時才處置；此動作會留下稽核紀錄。</p><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> 我已核對遠端確實沒有此登錄</label><label className="form-field">處置原因<input maxLength={DISPOSAL_REASON_MAX} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="button compact" disabled={busy||c.busy||!disposalReady(confirmed,reason)} onClick={()=>void dispose(r.id)}>確認未建立並處置</button></div>:<button className="button compact" disabled={busy||c.busy} onClick={()=>setDisposing(r.id)}>確認遠端未建立…</button>)}</article>)}{message&&<p role="status">{message}</p>}</section>;
}
