import {useState} from 'react';
import {api,ApiError} from './api';
import {draftKey,useDraft} from './drafts';
import {executionAllowed} from './ProjectExecution';
import type {Node,Project,Session,Workspace} from './types';
type Context={w:Workspace;s:Session;busy:boolean;refresh:()=>Promise<void>};
export function InputRegistration({c,p,n,canSubmit}:{c:Context;p:Project;n:Node;canSubmit:boolean}){
 const[draft,setDraft]=useDraft(draftKey(c.s,c.w,`input-registration:${p.id}:${n.id}`),{label:'',value:'',request_id:crypto.randomUUID(),attempted:false});const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
 const enabled=c.s.mode==='lark'&&(c.w.environment==='production'||(c.w.environment==='test'&&c.w.settings.test_connection_mode==='isolated_live'))&&executionAllowed(p,c.w)&&canSubmit;
 const rows=(c.w.input_revisions||[]).filter((r:any)=>r.project_id===p.id&&r.node_id===n.id&&r.key==='work_input');
 const labels:Record<string,string>={queued:'等待登錄',running:'登錄中',succeeded:'已登錄並核實',outcome_unknown:'結果待核實',blocked:'登錄受阻',failed:'登錄失敗',simulated:'模擬登錄'};
 const oversized=new TextEncoder().encode(JSON.stringify(draft.value)).length>50000;
 const submit=async()=>{if(oversized){setMessage('Input 內容超過 50KB，請縮短內容或使用文件交付');return}setBusy(true);setMessage('');setDraft({...draft,attempted:true});try{await api(`/api/projects/${encodeURIComponent(p.id)}/nodes/${encodeURIComponent(n.id)}/inputs`,{method:'POST',body:JSON.stringify({version:c.w.version,project_version:p.concurrency_version,request_id:draft.request_id,key:'work_input',label:draft.label,value:draft.value})});await c.refresh();setDraft({label:'',value:'',request_id:crypto.randomUUID(),attempted:false});setMessage('已交由背景工作登錄，請查看下方核實狀態。')}catch(e){if(e instanceof ApiError&&[401,403,409,422].includes(e.status)&&!draft.attempted)setDraft({...draft,attempted:false});if(e instanceof ApiError&&[401,409].includes(e.status))await c.refresh();setMessage((e as Error).message)}finally{setBusy(false)}};
 const reconcile=async(id:string)=>{setBusy(true);setMessage('');try{await api(`/api/input-revisions/${encodeURIComponent(id)}/reconcile`,{method:'POST',body:JSON.stringify({version:c.w.version,project_version:p.concurrency_version})});await c.refresh();setMessage('已查回原登錄結果，未另建立紀錄。')}catch(e){if(e instanceof ApiError&&[401,409].includes(e.status))await c.refresh();setMessage((e as Error).message)}finally{setBusy(false)}};
 const clearDraft=()=>{setDraft({label:'',value:'',request_id:crypto.randomUUID(),attempted:false});setMessage('已清除未送出的草稿，可以重新填寫。')};
 return <section aria-label="作業資料登錄"><h3>作業資料登錄</h3><p>交付資料會保留版本與提交人，並在下方顯示登錄狀態。</p>{enabled&&<form className="ops-form" onSubmit={e=>{e.preventDefault();void submit()}}><label className="form-field">資料名稱<input required maxLength={200} disabled={draft.attempted} value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})}/></label><label className="form-field">作業資料內容<textarea required maxLength={20000} disabled={draft.attempted} value={draft.value} onChange={e=>setDraft({...draft,value:e.target.value})}/></label>{oversized&&<p role="alert">內容超過 50KB，請縮短內容或使用文件交付。</p>}{draft.attempted&&<p>保留原提交識別與內容，重試只查核同一次提交，避免重複登錄。</p>}<button className="button" disabled={busy||c.busy||oversized||!draft.label.trim()||!draft.value.trim()}>{busy?'處理中…':draft.attempted?'重試確認送交結果':'提交作業資料'}</button>{!draft.attempted&&(draft.label||draft.value)&&<button type="button" className="button" disabled={busy||c.busy} onClick={clearDraft}>清除草稿重新填寫</button>}</form>}{rows.map((r:any)=><article className="ops-input" key={r.id}><strong>{r.label}</strong><p>{typeof r.value==='string'?r.value:'已保存結構化資料'}</p><p>{labels[r.status]||'狀態待核對'} · {r.created_at}</p>{enabled&&r.status==='outcome_unknown'&&<button className="button compact" disabled={busy||c.busy} onClick={()=>void reconcile(r.id)}>查回核實原登錄</button>}</article>)}{message&&<p role="status">{message}</p>}</section>;
}
