import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import {AppErrorBoundary} from './AppErrorBoundary';
import './design/tokens.css';
import './styles.css';
import './workbench.css';
import './brand-workspace.css';
import './company-workspace.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><AppErrorBoundary><App /></AppErrorBoundary></React.StrictMode>);
