import {ProjectExecutionNotice, executionAllowed} from './ProjectExecution';
import {projectQuotes} from './sourceQuotes';
import {ProjectReadiness, SourceContractIndex} from './ProjectReadiness';
import {useEffect, useState, useRef, type FormEvent} from 'react';
import {ArrowRight, ArrowUpRight, CalendarDays, Check, CheckCheck, ChevronDown, ChevronLeft, ChevronRight, CircleCheck, Clock3, Download, ExternalLink, FileCheck2, FilePlus2, GitBranch, Link2, Loader2, MessageSquare, Network, Pause, Play, Plus, Send, ShieldCheck, SlidersHorizontal, TriangleAlert, Upload, Users, X} from 'lucide-react';
import {useViewData} from './viewData';
import {api, perfMark} from './api';
import {ProjectOperations, ActionForm, Field as OpsField} from './Operations';
import {useDialogFocus} from './useDialogFocus';
import {MentionComposer, MentionTags, MentionDelivery} from './MentionComposer';
import {Avatar} from './AppShell';
import {NativeApprovalControls, FinancialApprovalRequests} from './NativeApprovalControls';
import {AuditTrail} from './AuditTrail';
import {FilePanel, FileModal} from './FileWorkspace';
import {DailyRecords} from './DailyRecords';
import {TaskBatchCompletion} from './TaskBatchCompletion';
import {draftKey, useDraft} from './drafts';
import {lifecycleGate} from './sourceLifecycle';
import {type Approval, type Node, type Project, type Task, type Workspace} from './types';
import {Ctx,active,progress,date,nameOf,money,openTask,TaskIcon,isLate,shortDate,Empty,EventList,ProjectSlice,Badge,NODE_NAMES,elapsed,isProjectLead,Primary,TaskTable,safeUrl,num,taskReadiness,isTaskActor,allTasks,Modal,STATUS,Field,TaskRow,OwnerSelect,eventMessage,stamp,unmatchedDaily} from './appCommon';
import {NextAction} from './DailyHome';
import {Badge as Tag,Button,Progress,Row,Section,Skeleton,Stat} from './design';
import './ProjectDetail.css';
import {ApprovalList} from './App';

export function CaseOverview({c,p}:{c:Ctx;p:Project}){
 const tasks=p.nodes.flatMap(n=>n.tasks.map(t=>({p,n,t}))).filter(r=>active(r.t)).sort((a,b)=>(a.t.due_date||'9999').localeCompare(b.t.due_date||'9999')).slice(0,4);
 const total=p.nodes.flatMap(n=>n.tasks).filter(t=>t.status!=='superseded');const completed=total.filter(t=>t.status==='completed').length;
 const navigate=(tab:string)=>c.go({view:'project',project:p.id,tab});

 const overdueCount=tasks.filter(r=>isLate(r.t,c.w.as_of)).length;
 const facts:[string,string][]=[['案件性質',p.case_type==='intake'?'待確認接案':'正式案件'],['有效期限',date(p.due_date)],['專案經理',nameOf(c.w,p.pm_id)],['合約金額',money(p.contract_amount)],...(p.parent_code?[['母案',p.parent_code] as [string,string]]:[])];
 return <div className="case-overview"><NextAction c={c} rows={p.nodes.flatMap(n=>n.tasks.map(t=>({p,n,t})))}/>
 <Section title={overdueCount?`待處理任務 · ${overdueCount} 項逾期`:"待處理任務"}>{tasks.map(r=><Row key={r.t.id} icon={<TaskIcon status={r.t.status}/>} label={r.t.title} detail={`${r.n.name} · ${nameOf(c.w,r.t.owner_id)}`} value={isLate(r.t,c.w.as_of)?<Tag tone="critical">{shortDate(r.t.due_date)}</Tag>:shortDate(r.t.due_date)} onClick={()=>openTask(c,r)}/>)}{!tasks.length&&<Empty title="目前沒有待處理任務"/>}<Row label="全部任務" icon={<ArrowUpRight size={17}/>} onClick={()=>navigate('flow')}/></Section>
 <Section title="案件摘要" footer="同案多份報價集中查看，不重複建立案件。"><div className="co-progress"><Stat label="任務完成度" value={<>{progress(p)}<small>%</small></>}/><Progress value={progress(p)} label="任務完成度"/><p>{completed} / {total.length} 項任務完成</p></div>{facts.map(([k,v])=><Row key={k} label={k} value={v}/>)}<div className="co-actions"><Button variant="primary" onClick={()=>navigate('flow')}>流程與交付<ArrowRight size={16}/></Button><Button onClick={()=>navigate('quotes')}>報價（{projectQuotes(c.w,p).length}）</Button></div></Section>
 <ProjectReadiness w={c.w} p={p}/>
 <Section title="案件活動"><EventList c={c} project={p.id} limit={3}/><Row label="全部" icon={<ArrowUpRight size={17}/>} onClick={()=>navigate('logs')}/></Section>
 <Section title="資料與關係"><Row label="基本資料" onClick={()=>navigate('basic')} value={<ChevronRight size={16}/>}/><Row label="母子案關係" onClick={()=>navigate('family')} value={<ChevronRight size={16}/>}/><Row label="日報紀錄" onClick={()=>navigate('daily')} value={<>{p.daily_reports.length} <ChevronRight size={16}/></>}/></Section></div>
}
export function ProjectDetailGate({c}:{c:Ctx}){
 // Shell mode reads only this project (tree plus its own approvals, events and records); a full workspace, after any mutation, takes the legacy path unchanged.
 const shell=c.w.scope==='shell';const id=c.route.project;
 const detail=useViewData<ProjectSlice|undefined>(shell?`project:${id}`:'project-legacy',(signal,current)=>shell&&id?api<ProjectSlice>(`/api/projects/${encodeURIComponent(id)}`,{signal},current):Promise.resolve(undefined),[c.reloadVersion]);
 useEffect(()=>{if(shell&&detail.data)perfMark('project-detail-render')},[shell,detail.data]);
 if(!shell)return <ProjectDetail c={c}/>;
 if(!detail.data)return detail.error?<Empty title={detail.error.includes('找不到')?'找不到這個案件':'案件讀取失敗'} detail={detail.error.includes('找不到')?'案件連結可能已失效，請回到案件總覽重新開啟。':detail.error}/>:<div className="project-detail" role="status"><p className="co-loading">正在讀取案件…</p><Skeleton height="2.5rem" width="60%"/><Skeleton lines={4}/></div>;
 const {scope:_scope,version:_version,as_of:_asOf,project,...records}=detail.data;
 return <ProjectDetail c={{...c,w:{...c.w,...records,projects:c.w.projects.map(p=>p.id===project.id?project:p)}}}/>;
}
export function ProjectDetail({c}:{c:Ctx}){
 const p=c.w.projects.find(p=>p.id===c.route.project);const[modal,setModal]=useState(c.route.focus?'complete-node':'');useEffect(()=>{if(c.route.focus)setModal('complete-node')},[c.route.focus,c.route.node]);const[approvalType,setApprovalType]=useState<'change'|'extension'>('change');const[expanded,setExpanded]=useState<Record<string,boolean>>({});
 if(!p)return <Empty title="找不到這個案件" detail="案件連結可能已失效，請回到案件總覽重新開啟。"/>;
 const selected=p.nodes.find(n=>n.id===c.route.node)||p.nodes.find(n=>n.status==='in_progress')||p.nodes[0];
 const tab=c.route.tab||'overview';const dataSection=tab==='data'?(c.route.section||'basic'):'';const selectedTask=p.nodes.flatMap(n=>n.tasks.map(t=>({p,n,t}))).find(r=>r.t.id===c.route.task);const approvals=c.w.approvals.filter(a=>a.project_id===p.id);const total=p.nodes.flatMap(n=>n.tasks).filter(t=>t.status!=='superseded');
 const nodeRoute=(n:Node)=>c.go({view:'project',project:p.id,node:n.id,tab:'flow'});
 const share=async()=>{try{await navigator.clipboard.writeText(location.href);c.notify('已複製此頁直達連結')}catch{c.notify('請複製瀏覽器網址列中的直達連結')}};
 return <div className="project-detail"><ProjectExecutionNotice p={p} w={c.w} s={c.s} run={c.run} busy={c.busy}/><div className="project-topline"><Button variant="plain" onClick={()=>c.go({view:'projects'})}><ChevronLeft size={15}/>案件總覽</Button><div className="project-tools"><span className="demo-inline">{p.source_kind==='demo'?'示範案件':p.case_type==='intake'?'待確認接案':'正式案件'}</span><button className="icon-button" title="複製直達連結" aria-label="複製直達連結" onClick={()=>void share()}><Link2 size={17}/></button><Button onClick={()=>setModal('participants')}><Users size={15}/>參與人員</Button></div></div><div className="project-title"><div><div className="case-code">{p.code}<span className="revision">v{p.revision}</span></div><h1>{p.name}</h1><div className="project-meta"><span>{p.client}</span><span className="separator"/><span><Avatar small user={c.w.users.find(u=>u.id===p.pm_id)}/>{nameOf(c.w,p.pm_id)}</span><span className="separator"/><span><CalendarDays size={14}/>{date(p.due_date)}</span></div></div><span className="project-source-status"><small>{p.source_kind==='demo'?'示範来源狀態':'來源狀態（V4）'}</small><Badge status={p.status} label={p.source_status||'來源待核對'}/></span></div>
 <nav className="project-tabs tabbar" aria-label="案件頁面">{[{key:'overview',label:'案件概覽'},{key:'flow',label:'流程與交付'},{key:'daily',label:'日報紀錄'},{key:'data',label:'案件資料'},{key:'logs',label:'操作紀錄'}].map(t=><button key={t.key} aria-current={tab===t.key?'page':undefined} className={tab===t.key?'active':''} onClick={()=>c.go({view:'project',project:p.id,node:selected?.id,tab:t.key})}>{t.label}</button>)}</nav>
 {tab==='data'&&<div className="case-data-navigation"><label>案件資料分類<select value={dataSection} onChange={e=>c.go({view:'project',project:p.id,node:selected?.id,tab:'data',section:e.target.value})}>{[['basic','基本資料'],['quotes',`報價（${projectQuotes(c.w,p).length}）`],['contracts','確認單與合約工項'],['family','母子案'],['participants','參與人員'],['files',`附件索引（${p.files.length}）`]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>}
 {c.route.completion===selected?.id&&modal!=='complete-node'&&<div className="completion-resume"><span>節點完成流程 · {NODE_NAMES[selected.key]||selected.name}</span><button className="text-button" onClick={()=>setModal('complete-node')}>返回逐項完成<ArrowRight size={15}/></button></div>}
 {tab==='overview'&&<CaseOverview c={c} p={p}/>}
 {dataSection==='contracts'&&<SourceContractIndex w={c.w} p={p}/>} {dataSection==='quotes'&&<QuotePanel c={c} p={p}/>} {dataSection==='family'&&<FamilyPanel c={c} p={p}/>}

 {tab==='flow'&&<><section className="major-approval-summary"><div><h2>重大事項審批</h2><p>一般成果依本地 SOP 確認；財務等重大確認、展延、設計變更與跳過走 Lark。</p></div><button className="button" onClick={()=>c.go({view:'project',project:p.id,node:selected?.id,tab:'flow',section:'approvals'})}>查看審批（{approvals.filter(a=>['draft','pending','approved'].includes(a.status)).length+(c.w.financial_requests||[]).filter((r:any)=>r.project_id===p.id&&['draft','pending','approved'].includes(r.status)).length}）</button>{approvals.filter(a=>['pending','approved'].includes(a.status)).map(a=><p key={a.id}>{a.title} · {a.status==='approved'?'已核准，待套用':'審批中'}</p>)}</section><div className="flow-heading"><div><h2>案件流程</h2><p>{p.nodes.length} 個階段 · {total.filter(t=>t.status==='completed').length}/{total.length} 項任務已完成</p></div><div className="flow-legend"><span><i className="green-dot"/>已完成</span><span><i className="purple-dot"/>進行中</span><span><i className="gray-dot"/>未開始</span></div></div><div className="workflow-scroll"><div className="workflow"><div className="flow-group front">{p.nodes.slice(0,3).map((n,i)=><div className="flow-unit" key={n.id}><StageButton n={n} selected={selected?.id===n.id} c={c} onClick={()=>nodeRoute(n)}/>{i<2&&<ArrowRight size={17} className="flow-arrow"/>}</div>)}</div><ArrowRight size={18} className="flow-arrow main-arrow"/><div className="production-group"><div className="production-label">生產作業 <span>依工項交接，可並行處理</span></div><div className="production-stages">{p.nodes.filter(n=>['field','control','mapping','report'].includes(n.key)).map(n=><StageButton key={n.id} n={n} selected={selected?.id===n.id} c={c} onClick={()=>nodeRoute(n)}/>)}</div></div><ArrowRight size={18} className="flow-arrow main-arrow"/><div className="flow-group end">{p.nodes.slice(7).map((n,i)=><div className="flow-unit" key={n.id}><StageButton n={n} selected={selected?.id===n.id} c={c} onClick={()=>nodeRoute(n)}/>{i===0&&<ArrowRight size={17} className="flow-arrow"/>}</div>)}</div></div></div>
 <div className="workflow-footer"><span><Clock3 size={14}/>流程經過 {elapsed(p.started_at||p.created_at,c.w.as_of)} 天 <small>· 日曆經過時間，非投入工時</small></span><button className="text-button" onClick={()=>{setApprovalType('change');setModal('approval')}}><GitBranch size={14}/>提出設計變更</button></div>
 {selected&&<section className="node-section"><div className="node-section-header"><div className="node-title"><span className="node-index">{String(p.nodes.indexOf(selected)+1).padStart(2,'0')}</span><div><h2>{NODE_NAMES[selected.key]||selected.name}<Badge status={selected.status}/></h2><p><span>{nameOf(c.w,selected.owner_id)}</span>負責 · {date(selected.start_date)} — {date(selected.due_date)}{selected.started_at&&<span> · 已停留 {elapsed(selected.started_at,selected.completed_at||c.w.as_of)} 天</span>}</p></div></div><fieldset className="node-actions" disabled={!executionAllowed(p,c.w)}><button className="button compact" onClick={()=>{setApprovalType('extension');setModal('approval')}}><Clock3 size={14}/>申請展延</button><button className="button compact" onClick={()=>setModal('addtask')} disabled={!isProjectLead(c.s,p)&&selected.owner_id!==c.s.user?.id}><Plus size={15}/>增補任務</button><Primary busy={c.busy} disabled={selected.status==='completed'||['pricing','settlement'].includes(selected.key)} onClick={()=>setModal('complete-node')}><CheckCheck size={15}/>完成節點</Primary></fieldset></div>
 <div className="node-guidance"><ShieldCheck size={15}/><span>必做任務及必要成果完成後，由節點負責人確認交接。</span><button className="text-button" onClick={()=>setExpanded(x=>({...x,[selected.id]:!x[selected.id]}))}>{expanded[selected.id]?'收合節點說明':'查看節點說明'}<ChevronDown size={13}/></button></div>{expanded[selected.id]&&<div className="node-description"><p>本節點採 SOP 範本任務，可依案件增補。日報是作業紀錄，不代表交付完成；受設計變更影響的工項需完成審批及版本切換後接續。</p><dl><dt>輸入</dt><dd>上游成果及本節點 作業資料</dd><dt>輸出</dt><dd>子任務完成說明及 成果檔案</dd><dt>協作人員</dt><dd>{selected.collaborator_ids.map(id=>nameOf(c.w,id)).join('、')||'尚未設定'}</dd></dl><button className="text-button" onClick={()=>c.go({view:'project',project:p.id,node:selected.id,tab:'files'})}>開啟 作業資料與成果<ArrowRight size={14}/></button></div>}
 <TaskBatchCompletion w={c.w} s={c.s} rows={selected.tasks.map(t=>({p,n:selected,t}))} busy={c.busy} run={c.run}/><TaskTable c={c} rows={selected.tasks.map(t=>({p,n:selected,t}))} showProject={false}/><div className="table-footer"><span>{selected.tasks.length} 項任務 · {selected.tasks.filter(t=>t.required&&t.status!=='superseded').length} 項必做</span><span>點擊任務查看詳情、成果及評論</span></div></section>}{selected&&<ProjectOperations key={`${selected.id}-${c.route.section||'review'}`} c={c} p={p} n={selected} initialSection={c.route.section}/> }
 <section className="project-discussion"><div className="section-heading"><h2>案件討論</h2><MessageSquare size={17} className="muted"/></div><Comments c={c} p={p}/></section></>}
 {dataSection==='basic'&&<div className="detail-page-content"><div className="section-heading"><div><h2>基本資料</h2><p>保留來源關係，不重複填寫已知資訊</p></div>{safeUrl(p.source_url)&&<a className="button" href={p.source_url} target="_blank" rel="noreferrer">開啟來源<ExternalLink size={15}/></a>}</div><div className="definition-grid">{[['案件編號',p.code],['業主',p.client],['專案經理',nameOf(c.w,p.pm_id)],['案件版本',`v${p.revision}`],['合約金額',money(p.contract_amount)],['預估營業額',`${num(p.estimated_points)} 點`],['目前有效期限',date(p.due_date)],['原始期限',date(p.original_due_date)],['開始日期',date(p.started_at)],['資料來源',p.source_kind==='demo'?'獨立示範資料':'報價總表／V4']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</div><div className="description-block"><h3>案件說明</h3><p>{p.description||'尚未填寫案件說明'}</p></div><div className="info-callout"><Network size={19}/><div><strong>金額、成本與點數分開追蹤</strong><p>合約金額為案件層資料。子任務點數依來源或指派設定，不重複累加為合約營收。</p></div></div></div>}
 {dataSection==='participants'&&<div className="detail-page-content"><div className="section-heading"><div><h2>案件參與人員</h2><p>各節點負責人作為子任務預設指派；個別改派保留。</p></div><Primary disabled={!isProjectLead(c.s,p)} onClick={()=>setModal('participants')}><Users size={16}/>統一設定人員</Primary></div><table className="data-table"><thead><tr><th>節點</th><th>負責人</th><th>協作人員</th><th>任務</th></tr></thead><tbody>{p.nodes.map(n=><tr key={n.id}><td><strong>{NODE_NAMES[n.key]}</strong></td><td><span className="person-cell"><Avatar small user={c.w.users.find(u=>u.id===n.owner_id)}/>{nameOf(c.w,n.owner_id)}</span></td><td>{n.collaborator_ids.map(id=>nameOf(c.w,id)).join('、')||<span className="muted">尚未設定</span>}</td><td>{n.tasks.filter(t=>t.status!=='superseded').length} 項</td></tr>)}</tbody></table></div>}
 {dataSection==='files'&&<FilePanel c={c} p={p} node={selected}/>}{tab==='daily'&&<DailyRecords key={p.id} w={c.w} p={p} go={c.go}/>}{tab==='logs'&&<AuditTrail key={p.id} w={c.w} p={p}/>}{tab==='flow'&&c.route.section==='approvals'&&<div className="detail-page-content"><div className="section-heading"><div><h2>關聯審批</h2><p>審批通過後，由負責人明確套用新版本或新期限。</p></div><div className="heading-actions"><button className="button" onClick={()=>{setApprovalType('extension');setModal('approval')}}><Clock3 size={16}/>申請展延</button><Primary onClick={()=>{setApprovalType('change');setModal('approval')}}><GitBranch size={16}/>設計變更</Primary></div></div><ApprovalList c={c} approvals={approvals}/><FinancialApprovalRequests c={c} p={p}/></div>}
 {selectedTask&&<TaskInspector key={selectedTask.t.id} c={c} row={selectedTask} onClose={()=>c.go({view:'project',project:p.id,node:selectedTask.n.id,tab})} onExtension={()=>{c.go({view:'project',project:p.id,node:selectedTask.n.id,tab});setApprovalType('extension');setModal('approval')}}/>}
 {c.route.task&&!selectedTask&&<div className="error-banner"><TriangleAlert size={17}/>找不到此任務，請從列表重新選擇。</div>}
 {modal==='participants'&&<ParticipantsModal c={c} p={p} onClose={()=>setModal('')}/>}{modal==='addtask'&&selected&&<AddTaskModal c={c} p={p} node={selected} onClose={()=>setModal('')}/>}{modal==='approval'&&<ApprovalForm c={c} p={p} node={selected} type={approvalType} onClose={()=>setModal('')}/>}{selected&&<NodeCompletion key={`${p.id}-${selected.id}-${c.s.user?.id}`} c={c} p={p} node={selected} open={modal==='complete-node'} onClose={()=>setModal('')} onNavigate={(nextTab,section,task)=>{setModal('');c.go({view:'project',project:p.id,node:selected.id,tab:nextTab,section,task,completion:selected.id})}}/>}
 </div>
}
export function StageButton({n,selected,c,onClick}:{n:Node;selected:boolean;c:Ctx;onClick:()=>void}){const ts=n.tasks.filter(t=>t.status!=='superseded');const p=c.w.projects.find(p=>p.nodes.some(node=>node.id===n.id));const pending=ts.filter(active);const actionable=p&&pending.some(t=>!taskReadiness({p,n,t},c));const owned=pending.some(t=>isTaskActor(t,c));const stepLabel=n.status==='completed'?'已完成':n.status==='approved_skipped'?'核准跳過':actionable?'待你處理':owned?'待補齊條件':pending.length?'待他人處理':'待節點確認';return <button className={`stage-button ${selected?'selected':''} ${n.status}`} onClick={onClick}><span className="stage-button-top"><TaskIcon status={n.status}/><strong>{NODE_NAMES[n.key]||n.name}</strong>{n.status==='completed'&&<Check size={13}/>}</span><span className="stage-action-label">{stepLabel}</span><span className="stage-button-bottom">{nameOf(c.w,n.owner_id)}<small>{ts.filter(t=>t.status==='completed').length}/{ts.length}</small></span>{n.status==='approved_skipped'&&<span className="stage-paused-count">核准跳過 · 任務成果保留</span>}{ts.some(t=>t.status==='paused')&&<span className="stage-paused-count">局部暫停 {ts.filter(t=>t.status==='paused').length} 項</span>}</button>}

export function NodeCompletion({c,p,node,open,onClose,onNavigate}:{c:Ctx;p:Project;node:Node;open:boolean;onClose:()=>void;onNavigate:(tab:string,section?:string,task?:string)=>void}){
 const required=node.tasks.filter(t=>t.required&&t.status!=='superseded');
 const unfinished=required.filter(t=>t.status!=='completed');
 const[firstTask]=useState(()=>node.tasks.some(t=>t.id===c.route.focus)?c.route.focus!:unfinished.find(t=>isTaskActor(t,c)&&!taskReadiness({p,n:node,t},c))?.id||unfinished[0]?.id||'');
 const[selectedId,setSelectedId]=useState(firstTask);const[drafts,setDrafts]=useDraft<Record<string,string>>(draftKey(c.s,c.w,`node:${p.id}:${node.id}:v${p.revision}`),{});const[fileMode,setFileMode]=useState('');const[attempted,setAttempted]=useState(false);const[notice,setNotice]=useState('');const[submitted,setSubmitted]=useState(false);const[skipDraft,setSkipDraft]=useDraft(draftKey(c.s,c.w,`skip:${p.id}:${node.id}:v${p.revision}`),{reason:'',impact:'',voteReason:''});const skipDirty=Object.values(skipDraft).some(text=>!!text.trim());
 useEffect(()=>{if(c.route.focus&&node.tasks.some(t=>t.id===c.route.focus))setSelectedId(c.route.focus)},[c.route.focus,node.id]);
 const dirty=skipDirty||Object.entries(drafts).some(([id,text])=>text!==(node.tasks.find(t=>t.id===id)?.output||''));
 useEffect(()=>{c.registerDrafts({projectId:p.id,nodeId:node.id,dirty});return()=>c.registerDrafts(null)},[dirty,p.id,node.id,c.registerDrafts]);
 const chooseTask=(id:string)=>setSelectedId(id);
 const task=node.tasks.find(t=>t.id===selectedId);const current=task&&task.status!=='completed'&&task.status!=='superseded'?task:undefined;
 const summary=(c.w.policy_summary||[]).find((item:{project_id:string})=>item.project_id===p.id)?.nodes.find((item:{id:string})=>item.id===node.id);
 const otherMissing=(summary?.missing||[]).filter((item:string)=>item!=='必做 SOP 尚未完成');
 const output=current?(drafts[current.id]??current.output??''):'';const canAct=!!current&&isTaskActor(current,c);
 const dependencies=current?allTasks(c.w).filter(r=>r.p.id===p.id&&(current.input_task_ids as string[]|undefined)?.includes(r.t.id)&&!(r.t.status==='completed'&&r.t.output)):[];
 const permit=[...(p.evidence||[])].reverse().find((e:{node_id:string;key:string;withdrawn?:boolean})=>e.node_id===node.id&&e.key==='permits'&&!e.withdrawn);
 const permitMissing=node.key==='field'&&(!permit||!['accepted','not_applicable'].includes(permit.status));
 const paused=current?.status==='paused'||!!lifecycleGate(p);
 const canSubmit=!['pricing','settlement'].includes(node.key)&&(isProjectLead(c.s,p)||c.s.user?.id===p.admin_id||[node.owner_id,node.supervisor_id,...node.collaborator_ids,...node.tasks.map(t=>t.owner_id)].includes(c.s.user?.id||''));
 const stage=(item:string)=>/SOP 期限/.test(item)?'deadlines':/Input/.test(item)?'inputs':/確認單/.test(item)?'issue':/財務|收付款|請款/.test(item)?'finance':'review';
 const complete=async()=>{if(!current)return;setAttempted(true);setNotice('');const result=await c.run('task_complete',{output},{project_id:p.id,node_id:node.id,task_id:current.id});if(!result)return;const updated=result.projects.find(x=>x.id===p.id)?.nodes.find(x=>x.id===node.id);const next=updated?.tasks.filter(t=>t.required&&active(t));const nextTask=next?.find(t=>isTaskActor(t,{...c,w:result})&&t.status!=='paused')||next?.[0];setSelectedId(nextTask?.id||'');setAttempted(false);setNotice(`已完成「${current.title}」${nextTask?'，接著處理下一項。':'，請核對節點交付條件。'}`)};
 const submit=async()=>{setAttempted(true);const result=await c.run('node_complete',{}, {project_id:p.id,node_id:node.id});if(result){setAttempted(false);setSubmitted(true);setNotice('已送交節點確認，尚待指定人員確認通過。')}};
 if(!open)return null;
 return <><Modal wide title={`完成「${NODE_NAMES[node.key]||node.name}」節點`} subtitle="逐項補齊小任務，再核對交付條件並送交節點確認。" onClose={onClose}><div className="modal-body node-completion"><div className="completion-progress"><span><strong>{required.length-unfinished.length}</strong> / {required.length} 項必做任務完成</span><span>{unfinished.length?`尚餘 ${unfinished.length} 項`:'任務已齊備'}</span></div>{notice&&<p className="completion-notice" role="status">{notice}</p>}{attempted&&c.error&&<p className="completion-error" role="alert">{c.error}</p>}
 {!submitted&&<div className="completion-layout"><nav className="completion-tasks" aria-label="逐項完成任務">{required.map((t,i)=><button key={t.id} className={selectedId===t.id?'selected':''} onClick={()=>{chooseTask(t.id);setAttempted(false);setNotice('')}} aria-current={selectedId===t.id?'step':undefined}><span className="completion-number">{t.status==='completed'?<Check size={16}/>:i+1}</span><span><strong>{t.title}</strong><small>{nameOf(c.w,t.owner_id)} · {STATUS[t.status]||t.status}</small></span></button>)}<button className={!selectedId?'selected':''} onClick={()=>{chooseTask('');setAttempted(false)}}><span className="completion-number"><ShieldCheck size={16}/></span><span><strong>節點交付檢核</strong><small>文件、變更與指定確認</small></span></button>{!['pricing','settlement'].includes(node.key)&&<button className={selectedId==='__skip__'?'selected':''} onClick={()=>{chooseTask('__skip__');setAttempted(false)}}><span className="completion-number"><GitBranch size={16}/></span><span><strong>申請跳過此節點</strong><small>PM 與該組主管共同核准</small></span></button>}</nav>
 <section className="completion-editor">{selectedId==='__skip__'?<NodeSkipPanel c={c} p={p} node={node} onNavigate={onNavigate} draft={skipDraft} setDraft={setSkipDraft}/>:current?<><div className="completion-task-heading"><div><span className="section-kicker">任務內容</span><h3>{current.title}</h3>{current.activation_source==='schedule'&&!current.started_at&&<p>已依排程啟用 · 尚未記錄實際開始</p>}</div><Badge status={current.status}/></div><p className="completion-owner">負責人：{nameOf(c.w,current.owner_id)}{canAct&&current.owner_id!==c.s.user?.id?' · 目前以有效代理人處理':''}</p><div className="completion-description"><h4>作業說明</h4><p>{current.description||'依案件 SOP 執行，完成後填寫成果與交接說明。'}</p><h4>作業資料</h4><p>{current.input||'請參考節點檔案及上游交付資料。'}</p></div>
 {!canAct&&<div className="completion-block"><strong>此任務由 {nameOf(c.w,current.owner_id)} 完成</strong><p>你可檢視內容或前往責任與交接，不能代替未授權的負責人完成。</p><button className="text-button" onClick={()=>onNavigate('operations','roles')}>查看責任與交接<ArrowRight size={14}/></button></div>}
 {paused&&<div className="completion-block"><strong>目前暫停作業</strong><p>{lifecycleGate(p)?`${lifecycleGate(p)}，請先核對案件狀態。`:'此任務仍在設計變更範圍內，需先完成審批及版本處理。'}</p><button className="text-button" onClick={()=>onNavigate(lifecycleGate(p)?'basic':'approvals')}>查看{lifecycleGate(p)?'案件狀態':'關聯審批'}<ArrowRight size={14}/></button></div>}
 {dependencies.length>0&&<div className="completion-block"><strong>前置成果尚未交付</strong>{dependencies.map(r=><button className="text-button" key={r.t.id} onClick={()=>{onClose();c.go({view:'project',project:p.id,node:r.n.id,task:r.t.id,tab:'flow'})}}>{r.n.name} · {r.t.title}<ArrowUpRight size={14}/></button>)}</div>}
 {permitMissing&&<div className="completion-block"><strong>公務證明尚未核准</strong><button className="text-button" onClick={()=>onNavigate('operations','review')}>提交證明或申請不適用<ArrowRight size={14}/></button></div>}
 <Field label="成果與交接說明" hint="填寫已完成內容、檔案位置與交接事項；完成任務後會保存。"><textarea rows={5} aria-label="逐項成果與交接說明" value={output} onChange={e=>setDrafts(d=>({...d,[current.id]:e.target.value}))} disabled={!canAct||paused} placeholder="請填寫實際成果，不能只用勾選代替交付。"/></Field>
 <div className="completion-file-actions"><button className="text-button" onClick={()=>onNavigate('files')}>查看節點檔案<ArrowUpRight size={14}/></button>{canAct&&<><button className="button compact" onClick={()=>setFileMode('upload')}><Upload size={14}/>上傳成果檔案</button><button className="button compact" onClick={()=>setFileMode('link')}><Link2 size={14}/>加入成果連結</button></>}</div>
 <div className="completion-task-actions"><button className="text-button" onClick={()=>onNavigate('flow',undefined,current.id)}>完整任務內容<ArrowUpRight size={14}/></button>{['pending','rework'].includes(current.status)?<Primary busy={c.busy} disabled={!canAct||paused||dependencies.length>0||permitMissing} onClick={()=>{setAttempted(true);void c.run('task_start',{}, {project_id:p.id,node_id:node.id,task_id:current.id}).then(result=>{if(result){setAttempted(false);setNotice('已開始作業，填妥成果後即可完成並接續下一項。')}})}}><Play size={15}/>開始此任務</Primary>:<Primary busy={c.busy} disabled={!canAct||paused||dependencies.length>0||permitMissing||!output.trim()} onClick={()=>void complete()}><Check size={15}/>完成並前往下一項</Primary>}</div></>:task&&selectedId?<div className="completion-finished"><CircleCheck size={28}/><h3>{task.title}</h3><p>{task.status==='completed'?'此任務已完成':'此任務已留存為舊版'}</p><p>{task.output||'無成果說明'}</p><button className="button" onClick={()=>setSelectedId(unfinished[0]?.id||'')}>{unfinished.length?'處理下一項':'前往節點交付檢核'}<ArrowRight size={15}/></button></div>:<><div className="completion-task-heading"><h3>節點交付檢核</h3><ShieldCheck size={21}/></div>{unfinished.length>0&&<div className="completion-block"><strong>尚有 {unfinished.length} 項必做任務未完成</strong><button className="text-button" onClick={()=>setSelectedId(unfinished.find(t=>isTaskActor(t,c)&&t.status!=='paused')?.id||unfinished[0].id)}>繼續逐項處理<ArrowRight size={14}/></button></div>}{!summary?<div className="completion-block"><p>尚未取得檢核結果。</p><button className="button" onClick={()=>void c.refresh()}>重新取得檢核</button></div>:otherMissing.length?<><p className="completion-owner">下列條件仍需處理，點選即可前往對應頁面。</p><ul className="completion-gates">{otherMissing.map((item:string)=><li key={item}><span>{item}</span><button className="text-button" onClick={()=>onNavigate(/設計變更/.test(item)?'approvals':'operations',stage(item))}>前往處理<ArrowUpRight size={14}/></button></li>)}</ul></>:<p className="completion-ready">目前交付檢核已齊備。送出時仍會重新核對最新資料。</p>}<div className="completion-file-actions"><button className="button" onClick={()=>onNavigate('operations','review')}>查看審核與交付</button><button className="button" onClick={()=>onNavigate('files')}>查看案件附件</button></div><p className="completion-owner">送交確認後，仍需由指定確認人及適用主管通過；不會直接完成大節點。</p><Primary busy={c.busy} disabled={!summary||!!unfinished.length||!!otherMissing.length||!canSubmit} onClick={()=>void submit()}>送交節點確認<Send size={15}/></Primary></>}</section></div>}
 {submitted&&<div className="completion-finished"><CircleCheck size={32}/><h3>待指定人員確認</h3><p>小任務成果已保存，節點尚未完成。</p><button className="button primary" onClick={()=>onNavigate('operations','review')}>查看節點確認進度<ArrowRight size={16}/></button></div>}</div><footer><span className="muted">{unfinished.length?'已完成項目會立即保存；未送出的文字暫存於此分頁，24 小時後失效；登出會清除。':'交付與確認依實際檢核結果進行。'}</span><button className="button" onClick={onClose}>返回案件</button></footer></Modal>{fileMode&&<FileModal c={c} p={p} node={node} mode={fileMode} defaultDirection="output" onClose={()=>setFileMode('')}/>}</>
}

export function NodeSkipPanel({c,p,node,onNavigate,draft,setDraft}:{c:Ctx;p:Project;node:Node;onNavigate:(tab:string,section?:string,task?:string)=>void;draft:{reason:string;impact:string;voteReason:string};setDraft:(draft:{reason:string;impact:string;voteReason:string}|((before:{reason:string;impact:string;voteReason:string})=>{reason:string;impact:string;voteReason:string}))=>void}){
 const{reason,impact,voteReason}=draft;const setReason=(reason:string)=>setDraft(before=>({...before,reason}));const setImpact=(impact:string)=>setDraft(before=>({...before,impact}));const setVoteReason=(voteReason:string)=>setDraft(before=>({...before,voteReason}));const[attempted,setAttempted]=useState(false);
 const requests=(c.w.node_skip_requests||[]).filter((r:{project_id:string;node_id:string})=>r.project_id===p.id&&r.node_id===node.id).sort((a:{version:number},b:{version:number})=>b.version-a.version);
 const request=requests[0];const capability=c.w.approval_connection?.native_submit?.by_type?.node_skip;const simulated=c.s.mode==='demo'||capability?.simulation_available===true;const available=simulated||capability?.available===true;
 const eligible=!node.source_completed&&!['pricing','settlement'].includes(node.key)&&!['completed','superseded','approved_skipped'].includes(node.status);
 const canCreate=c.s.user?.role==='manager'||[p.pm_id,node.owner_id,node.supervisor_id].includes(c.s.user?.id||'');const canSubmit=!!request&&[request.created_by,p.pm_id].includes(c.s.user?.id||'');const canWithdraw=canSubmit;
 const seats=request?.seats||{pm:p.pm_id,supervisor:node.supervisor_id||p.supervisor_id};const distinct=!!seats.pm&&!!seats.supervisor&&seats.pm!==seats.supervisor;
 const labels:Record<string,string>={draft:'草稿',pending:'等待共同核准',approved:'已共同核准、待套用',applied:'已核准跳過',rejected:'已駁回',withdrawn:'已撤回',invalidated:'內容異動、已失效'};
 const invoke=async(action:string,payload:Record<string,unknown>)=>{setAttempted(true);const result=await c.run(action,payload,{project_id:p.id,node_id:node.id});if(result){setAttempted(false);setVoteReason('');if(action==='node_skip_create'){setReason('');setImpact('')}}};
 return <section className="node-skip-panel">{request&&!simulated&&<NativeApprovalControls c={c} kind="node_skip" item={request} canSubmit={canSubmit}/>}
<div className="completion-task-heading"><h3>申請跳過此節點</h3><GitBranch size={20}/></div><p className="completion-owner">由本案 PM 與該組主管兩位不同人共同核准，再由 PM 明確套用。原任務與成果會保留，前置成果條件不會自動解除。</p>{!available&&<div className="completion-block"><strong>Lark 送審待設定</strong><p>目前只能保存草稿，不會送出審批或跳過節點。正式審批與核准回傳驗證完成後才能送審。</p><button className="text-button" onClick={()=>c.go({view:'admin',tab:'settings'})}>查看串接設定<ArrowUpRight size={14}/></button></div>}{simulated&&<p className="completion-notice">本區為測試模擬，不會送往正式 Lark。</p>}{attempted&&c.error&&<p role="alert" className="completion-error">{c.error}</p>}
 <dl className="case-facts"><div><dt>案件 PM</dt><dd>{nameOf(c.w,seats.pm)}</dd></div><div><dt>該組主管</dt><dd>{nameOf(c.w,seats.supervisor)}</dd></div></dl>{!distinct&&<div className="completion-block"><strong>確認人尚未完整分派或為同一人</strong><p>請先指定兩位不同的 PM 與該組主管；不能由同一人投兩票。</p><button className="text-button" onClick={()=>onNavigate('operations','roles')}>前往責任與交接<ArrowRight size={14}/></button></div>}
 {request&&<div className="skip-request"><h4>申請 v{request.version} · {labels[request.status]||request.status}</h4><p><strong>原因：</strong>{request.reason}</p><p><strong>影響：</strong>{request.impact}</p>{request.invalidated_reason&&<p className="late-text">{request.invalidated_reason}</p>}<div className="skip-votes">{Object.entries(request.seats||{}).map(([seat,id])=>{const vote=[...(request.votes||[])].reverse().find(v=>v.seat===seat);return <p key={seat}>{seat==='pm'?'PM':'該組主管'} · {nameOf(c.w,String(id))}：{vote?(vote.result==='approved'?'已同意':'已駁回'):'待確認'}</p>})}</div>
 {simulated&&request.status==='draft'&&<Primary busy={c.busy} disabled={!available||!distinct||!canSubmit} onClick={()=>void invoke('node_skip_submit',{id:request.id})}>{simulated?'送出測試審批':'送出共同審批'}<Send size={15}/></Primary>}
 {request.status==='pending'&&!(request.votes||[]).some((v:{actor_id:string})=>v.actor_id===c.s.user?.id)&&Object.entries(request.seats||{}).some(([,id])=>id===c.s.user?.id)&&<><Field label="核准／駁回說明（駁回必填）"><textarea rows={3} value={voteReason} onChange={e=>setVoteReason(e.target.value)}/></Field>{Object.entries(request.seats||{}).filter(([,id])=>id===c.s.user?.id).map(([seat])=><div key={seat} className="inline-actions"><Primary busy={c.busy} disabled={!distinct} onClick={()=>void invoke('node_skip_vote',{id:request.id,seat,result:'approved',reason:voteReason})}>以{seat==='pm'?' PM ':'組主管'}身分同意</Primary><button className="button" disabled={c.busy||!voteReason.trim()} onClick={()=>void invoke('node_skip_vote',{id:request.id,seat,result:'rejected',reason:voteReason})}>駁回申請</button></div>)}</>}
 {request.status==='pending'&&(request.votes||[]).some((v:{actor_id:string})=>v.actor_id===c.s.user?.id)&&<p className="completion-notice">你已確認此申請，正在等待另一位指定人員。</p>}
 {request.status==='approved'&&<><p className="completion-owner">共同核准已完成，仍需 PM 明確套用才會改為「核准跳過」。</p><Primary busy={c.busy} disabled={c.s.user?.id!==request.seats.pm} onClick={()=>void invoke('node_skip_apply',{id:request.id})}>套用已核准的跳過</Primary></>}
 {request.status==='applied'&&<p className="completion-notice">此節點為「核准跳過」，不代表小任務或交付成果已完成。</p>}
 {['draft','pending','approved'].includes(request.status)&&!request.native_binding?.attempted&&canWithdraw&&<details className="skip-withdraw"><summary>撤回申請</summary><Field label="撤回原因"><textarea value={voteReason} onChange={e=>setVoteReason(e.target.value)}/></Field><button className="button" disabled={c.busy||!voteReason.trim()} onClick={()=>void invoke('node_skip_withdraw',{id:request.id,reason:voteReason})}>確認撤回申請</button></details>}</div>}
 {(!request||['rejected','withdrawn','invalidated'].includes(request.status))&&eligible&&<form onSubmit={e=>{e.preventDefault();void invoke('node_skip_create',{reason,impact})}}><Field label="跳過原因"><textarea required rows={3} value={reason} onChange={e=>setReason(e.target.value)} disabled={!canCreate}/></Field><Field label="對後續工項、交付及業主承諾的影響"><textarea required rows={3} value={impact} onChange={e=>setImpact(e.target.value)} disabled={!canCreate}/></Field><Primary type="submit" busy={c.busy} disabled={!canCreate||!reason.trim()||!impact.trim()}>保存跳過申請草稿</Primary></form>}{!eligible&&!request&&<p className="completion-block">此節點不適用跳過。財務與結案仍須完成原本的雙方確認及結清條件。</p>}</section>
}

export function TaskInspector({c,row,onClose,onExtension}:{c:Ctx;row:TaskRow;onClose:()=>void;onExtension:()=>void}){
 const{p,n,t}=row;const relatedChanges=c.w.approvals.filter(a=>a.project_id===p.id&&a.type==='change'&&((a as Approval&{affected_task_ids?:string[]}).affected_task_ids||a.task_ids).includes(t.id));const[output,setOutput]=useDraft(draftKey(c.s,c.w,`task:${p.id}:${t.id}:v${t.revision}`),t.output||'');const[reason,setReason]=useState('');const[returning,setReturning]=useState(false);const[editing,setEditing]=useState(false);const[tab,setTab]=useState(c.route.comment?'comments':'details');useEffect(()=>{if(c.route.comment)setTab('comments')},[c.route.comment]);const scope={project_id:p.id,node_id:n.id,task_id:t.id};const canAssign=isProjectLead(c.s,p)||n.owner_id===c.s.user?.id;const canAct=isTaskActor(t,c);
 const dialogRef=useDialogFocus(onClose);
 const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);const payload:Record<string,unknown>={};const values={title:String(d.get('title')),owner_id:String(d.get('owner_id')),description:String(d.get('description')),points:d.get('points')===''?null:Number(d.get('points'))};for(const [key,value] of Object.entries(values))if(value!==t[key])payload[key]=value;if(d.get('start_date')&&d.get('start_date')!==t.start_date)payload.start_date=d.get('start_date');if(!t.due_date&&d.get('due_date'))payload.due_date=d.get('due_date');if(await c.run('task_update',payload,scope))setEditing(false)};
 return <div className="drawer-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><aside ref={dialogRef} tabIndex={-1} className="task-inspector" role="dialog" aria-modal="true" aria-label={t.title}><header><div className="inspector-breadcrumb"><span>{p.code}</span><ChevronRight size={13}/><span>{NODE_NAMES[n.key]}</span></div><div><button className="icon-button" title="複製任務連結" aria-label="複製任務連結" onClick={()=>{void navigator.clipboard.writeText(location.href).then(()=>c.notify('已複製任務直達連結')).catch(()=>c.notify('請複製網址列中的連結'))}}><Link2 size={17}/></button><button className="icon-button" onClick={onClose} aria-label="關閉任務"><X size={19}/></button></div></header><div className="inspector-title"><span className="eyebrow">{t.required?'SOP TASK':'ADDITIONAL TASK'} · V{t.revision||1}</span><h2>{t.title}</h2><Badge status={t.status}/>{t.activation_source==='schedule'&&!t.started_at&&<p className="ops-notice">已依排程啟用 · 尚未記錄實際開始</p>}{isLate(t,c.w.as_of)&&<span className="late-tag">逾期 {elapsed(t.due_date,c.w.as_of)} 天</span>}</div><div className="tabbar inspector-tabs"><button className={tab==='details'?'active':''} onClick={()=>setTab('details')}>任務詳情</button><button className={tab==='comments'?'active':''} onClick={()=>setTab('comments')}>評論<span>{t.comments?.length||0}</span></button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>歷程</button></div><div className="inspector-content">
 {tab==='details'&&<>{editing?<form id="task-edit" onSubmit={e=>void save(e)}><Field label="任務名稱"><input name="title" defaultValue={t.title} required/></Field><Field label="負責人"><OwnerSelect w={c.w} name="owner_id" value={t.owner_id}/></Field><div className="form-row"><Field label="開始日期"><input name="start_date" type="date" defaultValue={t.start_date?.slice(0,10)||''} disabled={!!t.start_date}/></Field><Field label="有效期限" hint={t.due_date?'已排定期限需申請展延':''}><input name="due_date" type="date" defaultValue={t.due_date?.slice(0,10)||''} disabled={!!t.due_date}/></Field></div><Field label="營業額點數"><input name="points" type="number" min="0" step="0.01" defaultValue={t.points??''}/></Field><Field label="說明"><textarea name="description" rows={4} defaultValue={t.description}/></Field><div className="inline-actions"><button type="button" className="button" onClick={()=>setEditing(false)}>取消</button><Primary type="submit" busy={c.busy}>儲存指派與排程</Primary></div></form>:<>{canAct&&t.owner_id!==c.s.user?.id&&<div className="proxy-notice"><Users size={14}/>目前以有效代理人身份處理此任務</div>}<div className="inspector-fields"><div><dt>負責人</dt><dd><Avatar small user={c.w.users.find(u=>u.id===t.owner_id)}/>{nameOf(c.w,t.owner_id)}</dd></div><div><dt>排程</dt><dd>{date(t.start_date)} <ArrowRight size={13}/> {date(t.due_date)}</dd></div><div><dt>原始期限</dt><dd>{date(t.original_due_date)}</dd></div><div><dt>營業額點數</dt><dd>{num(t.points)} 點</dd></div><div><dt>工項關聯</dt><dd className="mono subtle-value">{(c.w.contract_items||[]).filter((item:any)=>t.contract_item_ids&&Array.isArray(t.contract_item_ids)&&t.contract_item_ids.includes(item.id)).map((item:any)=>item.title||'來源工項待核對').join('、')||(t.work_item_id?'來源工項待核對':'未連結工項')}</dd></div></div>{canAssign&&t.status!=='superseded'&&<button className="text-button inspector-edit" onClick={()=>setEditing(true)}><SlidersHorizontal size={14}/>調整指派與排程</button>}<div className="inspector-description"><h3>任務說明</h3><p>{t.description||'依案件 SOP 執行，完成後補上成果與交接說明。'}</p></div></>}
 <div className="io-block"><h3><Download size={16}/>作業資料</h3><p>{t.input||'請參考本節點 作業資料及上游交付資料。'}</p><button className="text-button" onClick={()=>c.go({view:'project',project:p.id,node:n.id,tab:'files'})}>查看節點檔案<ArrowUpRight size={14}/></button></div><div className="io-block"><h3><Upload size={16}/>成果與交接</h3><textarea aria-label="成果與交接說明" value={output} onChange={e=>setOutput(e.target.value)} rows={4} placeholder="描述已完成成果、檔案位置，以及下游需注意的事項…" disabled={!canAct||t.status==='superseded'}/><small>完成任務時會儲存此成果說明。</small></div>{t.status==='paused'&&<div className="info-callout amber"><Pause size={18}/><p>此工項因設計變更暫停。審批完成並切換新版後，才可接續作業。{relatedChanges.map(a=><button key={a.id} className="text-button" onClick={()=>c.go({view:'project',project:p.id,tab:'approvals',approval:a.id})}>查看「{a.title}」<ArrowUpRight size={14}/></button>)}{!relatedChanges.length&&<button className="text-button" onClick={()=>c.go({view:'project',project:p.id,tab:'approvals'})}>查看案件關聯審批<ArrowUpRight size={14}/></button>}</p></div>}{returning&&<div className="return-form"><Field label="退回原因"><textarea rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="說明需要補充或修正的部分…"/></Field><div className="inline-actions"><button className="button" onClick={()=>setReturning(false)}>取消</button><Primary busy={c.busy} disabled={!reason.trim()} onClick={()=>void c.run('task_return',{reason},scope).then(r=>{if(r)setReturning(false)})}>確認退回修正</Primary></div></div>}</>}
 {tab==='comments'&&<Comments c={c} p={p} n={n} t={t}/>}{tab==='history'&&<div className="event-list">{c.w.events.filter(e=>e.task_id===t.id).slice().reverse().map(e=><div className="event" key={e.id}><span className="event-dot"/><div><p>{eventMessage(e)}</p><small>{nameOf(c.w,e.actor_id)} · {stamp(e.created_at)}</small></div></div>)}{!c.w.events.some(e=>e.task_id===t.id)&&<Empty title="尚無任務異動"/>}</div>}
 </div><footer className="inspector-footer"><div><button className="button compact" onClick={onExtension} disabled={t.status==='superseded'}><Clock3 size={14}/>展延</button><button className="button compact" onClick={()=>{setTab('details');setReturning(true)}} disabled={!canAct||['superseded','paused'].includes(t.status)}>退回</button></div>{t.status==='pending'||t.status==='rework'?<Primary busy={c.busy} disabled={!canAct} onClick={()=>void c.run('task_start',{},scope)}><Play size={14}/>開始作業</Primary>:<Primary busy={c.busy} disabled={!canAct||['completed','paused','superseded'].includes(t.status)||!output.trim()} onClick={()=>void c.run('task_complete',{output},scope)}><Check size={15}/>{t.status==='completed'?'已完成':'完成任務'}</Primary>}</footer>{!canAct&&<div className="permission-note">完成作業由負責人或有效代理人操作</div>}</aside></div>
}
export function Comments({c,p,n,t}:{c:Ctx;p:Project;n?:Node;t?:Task}){const comments=t?.comments||p.comments||[];const storageKey=draftKey(c.s,c.w,`comment:${p.id}:${t?.id||(n?`node:${n.id}`:"project")}`);const targetRef=useRef<HTMLDivElement>(null);useEffect(()=>{if(!c.route.comment)return;const frame=requestAnimationFrame(()=>targetRef.current?.scrollIntoView({block:'center',behavior:'auto'}));return()=>cancelAnimationFrame(frame)},[c.route.comment]);return <div className="comments"><div className="comment-compose"><Avatar user={c.s.user||undefined}/><MentionComposer key={storageKey} storageKey={storageKey} users={c.w.users} busy={c.busy} onSubmit={async(body,mentions)=>!!await c.run('comment_add',{body,mentions},{project_id:p.id,node_id:n?.id,task_id:t?.id})}/></div>{comments.slice().reverse().map(comment=><div className={`comment ${c.route.comment===comment.id?'comment-target':''}`} key={comment.id} ref={c.route.comment===comment.id?targetRef:undefined} data-comment-id={comment.id}><Avatar small user={c.w.users.find(u=>u.id===comment.author_id)}/><div><header><strong>{nameOf(c.w,comment.author_id)}</strong><small>{stamp(comment.created_at)}</small></header><p>{comment.body}</p><MentionTags ids={comment.mentions} users={c.w.users}/><MentionDelivery notifications={comment.notifications} users={c.w.users}/></div></div>)}</div>}
export function ParticipantsModal({c,p,onClose}:{c:Ctx;p:Project;onClose:()=>void}){const[nodes,setNodes]=useState(p.nodes.map(n=>({node_id:n.id,owner_id:n.owner_id,collaborator_ids:[...n.collaborator_ids]})));const changed=nodes.filter(n=>{const before=p.nodes.find(x=>x.id===n.node_id)!;return n.owner_id!==before.owner_id||JSON.stringify(n.collaborator_ids.slice().sort())!==JSON.stringify(before.collaborator_ids.slice().sort())});const canEdit=isProjectLead(c.s,p);return <Modal title="統一設定參與人員" subtitle="節點負責人會作為預設指派；已個別改派的子任務保留原負責人。" onClose={onClose} wide><div className="modal-body"><div className="participants-editor">{nodes.map((n,i)=><div className="participant-edit-row" key={n.node_id}><strong>{NODE_NAMES[p.nodes[i].key]}</strong><OwnerSelect w={c.w} value={n.owner_id} disabled={!canEdit} onChange={v=>setNodes(ns=>ns.map(x=>x.node_id===n.node_id?{...x,owner_id:v}:x))}/><div className="collaborator-options">{c.w.users.filter(u=>u.id!==n.owner_id&&(u.active!==false||n.collaborator_ids.includes(u.id))).map(u=><label key={u.id}><input type="checkbox" checked={n.collaborator_ids.includes(u.id)} disabled={!canEdit||u.active===false} onChange={e=>setNodes(ns=>ns.map(x=>x.node_id===n.node_id?{...x,collaborator_ids:e.target.checked?[...x.collaborator_ids,u.id]:x.collaborator_ids.filter(id=>id!==u.id)}:x))}/>{u.name}{u.active===false&&'（已停用）'}</label>)}</div></div>)}</div></div><footer><span className="muted">{!canEdit?'需由本案專案經理或主管調整':changed.some(n=>!n.owner_id)?'請先指派變更節點的負責人':''}</span><button className="button" onClick={onClose}>取消</button><Primary busy={c.busy} disabled={!canEdit||!changed.length||changed.some(n=>!n.owner_id)} onClick={()=>void c.run('participants_update',{nodes:changed},{project_id:p.id}).then(r=>{if(r)onClose()})}>儲存參與人員</Primary></footer></Modal>}
export function AddTaskModal({c,p,node,onClose}:{c:Ctx;p:Project;node:Node;onClose:()=>void}){const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);const payload:Record<string,unknown>={title:d.get('title'),required:d.get('required')==='on',points:d.get('points')===''?null:Number(d.get('points'))};if(d.get('owner_id')&&d.get('owner_id')!==node.owner_id)payload.owner_id=d.get('owner_id');for(const k of ['start_date','due_date','work_item_id'])if(d.get(k))payload[k]=d.get(k);if(await c.run('task_add',payload,{project_id:p.id,node_id:node.id}))onClose()};return <Modal title={`增補任務 · ${NODE_NAMES[node.key]}`} subtitle="保留 SOP 範本，也可增加案件需要的作業。" onClose={onClose}><form onSubmit={e=>void submit(e)}><div className="modal-body"><Field label="任務名稱"><input name="title" required placeholder="例如：追加控制點複測" autoFocus/></Field><Field label="負責人"><OwnerSelect w={c.w} name="owner_id" value={node.owner_id}/></Field><div className="form-row"><Field label="開始日期"><input name="start_date" type="date"/></Field><Field label="有效期限"><input name="due_date" type="date"/></Field></div><div className="form-row"><Field label="營業額點數"><input name="points" type="number" min="0" step="0.01" placeholder="尚未設定"/></Field><Field label="所屬工項"><select name="work_item_id"><option value="">獨立 SOP 作業</option>{Array.from(new Set(p.nodes.flatMap(n=>n.tasks.map(t=>t.work_item_id)).filter(Boolean))).map(id=><option key={id} value={id}>{id}</option>)}</select></Field></div><label className="checkbox-line"><input name="required" type="checkbox" defaultChecked/>列為此節點的必做任務</label></div><footer><button className="button" type="button" onClick={onClose}>取消</button><Primary busy={c.busy} type="submit"><Plus size={15}/>新增任務</Primary></footer></form></Modal>}

export function ApprovalForm({c,p,node,type,onClose}:{c:Ctx;p:Project;node?:Node;type:'change'|'extension';onClose:()=>void}){
 const[ids,setIds]=useState<string[]>([]);const[newDate,setNewDate]=useState('');const[error,setError]=useState('');const rows=p.nodes.flatMap(n=>n.tasks.filter(t=>t.status!=='superseded').map(t=>({n,t})));const chosen=rows.filter(r=>ids.includes(r.t.id));const impacted=type==='change'?rows.filter(r=>chosen.some(ch=>ch.t.id===r.t.id||(ch.t.work_item_id&&ch.t.work_item_id===r.t.work_item_id&&p.nodes.indexOf(r.n)>=p.nodes.indexOf(ch.n)))):chosen;
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!ids.length){setError('請至少選擇一項受影響任務');return}if(type==='extension'&&!newDate){setError('請填寫申請期限');return}const d=new FormData(e.currentTarget);const result=await c.run('approval_create',{type,title:d.get('title'),reason:d.get('reason'),node_id:node?.id||chosen[0]?.n.id,task_ids:ids,dates:newDate?ids.map(task_id=>({task_id,due_date:newDate})):[],reference_url:d.get('reference_url')||'',attachments:[]},{project_id:p.id});if(result){onClose();c.go({view:'project',project:p.id,tab:'approvals'})}};
 return <Modal wide title={type==='change'?'提出設計變更':'申請期限展延'} subtitle={type==='change'?'指定影響範圍，送審後只暫停相關工項及下游。':'核准並套用前，所有任務仍依原有效期限執行。'} onClose={onClose}><form onSubmit={e=>void submit(e)}><div className="modal-body"><div className="form-row"><Field label="申請標題"><input name="title" required placeholder={type==='change'?'例如：新增測量範圍與成果版本':'例如：配合業主進場時程調整'} autoFocus/></Field><Field label={type==='change'?'新版申請期限（選填）':'申請期限'}><input type="date" value={newDate} required={type==='extension'} onChange={e=>setNewDate(e.target.value)}/></Field></div><Field label="申請原因"><textarea name="reason" required rows={3} placeholder="說明調整原因、影響與預計處理方式…"/></Field><div className="form-field"><span>選擇受影響任務 <em>{ids.length} 項</em></span><div className="task-picker">{p.nodes.map(n=><div key={n.id}><h4>{NODE_NAMES[n.key]}</h4>{n.tasks.filter(t=>t.status!=='superseded').map(t=><label key={t.id}><input type="checkbox" checked={ids.includes(t.id)} onChange={e=>setIds(current=>e.target.checked?[...current,t.id]:current.filter(id=>id!==t.id))}/><span>{t.title}<small>{nameOf(c.w,t.owner_id)} · 目前期限 {date(t.due_date)}</small></span><Badge status={t.status}/></label>)}</div>)}</div></div>{ids.length>0&&<div className={`impact-preview ${type==='change'?'amber':''}`}><h4><GitBranch size={15}/>{type==='change'?'送審後影響範圍':'期限調整範圍'} · {impacted.length} 項</h4><p>{type==='change'?'選定任務與相同工項的後續任務將暫停，其他工項繼續執行。':'待審期間繼續執行，原有效期限仍用來判定逾期。'}</p><div className="impact-tags">{impacted.map(r=><span key={r.t.id}>{NODE_NAMES[r.n.key]} · {r.t.title}</span>)}</div></div>}<Field label="既有 Lark 審批連結（選填）"><input name="reference_url" type="url" placeholder="https://…"/></Field>{error&&<p className="form-error">{error}</p>}</div><footer><span className="muted">先建立草稿，檢視後再送審</span><button className="button" type="button" onClick={onClose}>取消</button><Primary type="submit" busy={c.busy}><FilePlus2 size={15}/>建立申請草稿</Primary></footer></form></Modal>
}
export function nextWorkday(day:string,w:Workspace){const d=new Date(`${day.slice(0,10)}T00:00:00Z`);for(let i=0;i<40;i++){d.setUTCDate(d.getUTCDate()+1);const value=d.toISOString().slice(0,10);const weekday=d.getUTCDay();if(w.calendar.workdays.includes(value)||(!w.calendar.holidays.includes(value)&&weekday!==0&&weekday!==6))return value}return day}
export function DailyPanel({c,p}:{c:Ctx;p:Project}){const[fieldDay,setFieldDay]=useState(p.daily_reports.filter(r=>r.department.includes('外業')).map(r=>r.date).sort().at(-1)||c.w.as_of.slice(0,10));const expected=nextWorkday(fieldDay,c.w);const controls=p.daily_reports.filter(r=>r.department.includes('控制')&&r.date===expected&&r.case_code===p.code);const notYet=expected>c.w.as_of.slice(0,10);const sourceUncertain=p.source_kind!=='demo'&&(c.w.source_status.status!=='ready'||unmatchedDaily(c.w)>0);return <div className="detail-page-content"><div className="section-heading"><div><h2>日報作業紀錄</h2><p>目前以完整案號、日期及組別比對，不推論外業批次。</p></div></div><div className="daily-check"><div><label>外業作業日期<input type="date" value={fieldDay} onChange={e=>setFieldDay(e.target.value)}/></label><ArrowRight size={18}/><div><span>控制組應開始日期</span><strong>{date(expected)}<small>下一工作日</small></strong></div></div><Badge status={controls.length?'completed':sourceUncertain?'paused':notYet?'pending':'paused'} label={controls.length?'已有作業紀錄':sourceUncertain?'來源資料待確認':notYet?'尚未到檢查日':'尚無已配對作業紀錄'}/></div><div className="info-callout"><FileCheck2 size={18}/><p>{controls.length?`已查到 ${controls.length} 筆本案控制組紀錄。`:sourceUncertain?'來源尚未完整讀取或日報關聯待核對，目前無法確認本案作業紀錄。':'未查到紀錄不代表確定未作業，可由主管進一步追蹤。'} 日報有作業不代表成果完成；子任務仍需負責人確認。</p></div>{unmatchedDaily(c.w)>0&&<p className="ops-notice">來源共 {num(unmatchedDaily(c.w))} 筆日報待配對，本案是否有未配對作業仍需核對。<button className="text-button" onClick={()=>c.go({view:'admin',tab:'daily'})}>前往日報配對核對</button></p>}<table className="data-table"><thead><tr><th>日期</th><th>組別 / 人員</th><th>案號</th><th>作業內容</th><th>營業額點數</th><th>原日報檢核</th><th/></tr></thead><tbody>{p.daily_reports.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(r=><tr key={r.id}><td>{date(r.date)}</td><td>{r.department}<small>{r.person}</small></td><td className="mono">{r.case_code}{(r.match_basis==='provisional_case_code'||r.mapping_status==='provisional_case_code')&&<><small><Badge status="paused" label="暫填工編 · 來源待核對"/></small><small title="以暫填案號精確配對；原表正式關聯尚未修復。">原始案號：{r.source_case_code||'—'}</small></>}</td><td>{r.description}</td><td>{num(r.points)} 點</td><td><DailyReviewCell review={r.review}/></td><td>{safeUrl(r.source_url)&&<a className="icon-button" href={r.source_url} target="_blank" rel="noreferrer" aria-label="開啟來源日報"><ExternalLink size={16}/></a>}</td></tr>)}</tbody></table>{!p.daily_reports.length&&<Empty title="尚未配對到本案日報" detail={sourceUncertain?'請至資料來源查看日報紀錄與核對原表關聯。':undefined}/>}</div>}

export function DailyReviewCell({review}:{review?:import('./types').DailyReview}){
 const labels:Record<string,string>={approved:'已通過',accepted:'已通過',returned:'已退回',pending:'待檢核',unknown:'來源待核對',conflict:'檢核結果衝突'};
 const checks=review?.checks;
 return <><span>{labels[review?.status||'unknown']||review?.status}</span>{checks&&<details><summary>檢核明細</summary>{(Array.isArray(checks)?checks.map(x=>[x.label||x.name,x.value]):Object.entries(checks)).map(([name,value],i)=><small key={i}>{String(name)}：{value===true?'已檢核':value===false?'未檢核':value==null?'未提供':String(value)}</small>)}</details>}{safeUrl(review?.source_url)&&<a href={review!.source_url} target="_blank" rel="noreferrer">原日報檢核</a>}</>
}
export function QuotePanel({c,p}:{c:Ctx;p:Project}){
 const classify:Record<string,string>={effective:'有效報價',duplicate:'重複報價',additional:'追加報價'};
 const seats=[['pm',p.pm_id,'PM'],['sales',p.sales_id,'業務']].filter(([,id])=>id===c.s.user?.id);
 return <div className="detail-page-content operations"><h2>本案報價</h2><p>PM：{nameOf(c.w,p.pm_id)} · 業務：{nameOf(c.w,p.sales_id)}。來源金額不直接累加為合約金額；兩方須以不同操作者確認同一分類及來源版本。</p>{!projectQuotes(c.w,p).length?<Empty title="尚無已配對報價" detail="來源同步完成後顯示可追溯的報價紀錄。"/>:<table className="data-table"><thead><tr><th>報價編號</th><th>工程編號</th><th>來源金額</th><th>確認狀態</th><th>來源</th></tr></thead><tbody>{projectQuotes(c.w,p).map(q=>{const reviews=(p.quote_reviews||[]).filter((r:any)=>r.quote_id===q.id);return <tr key={q.id}><td>{q.quote_code}{(q as any).confirmation_count>0&&<small>關聯 {(q as any).confirmation_count} 份工程確認單</small>}{(q as any).source_missing&&<small>來源已移除，保留歷史</small>}</td><td>{q.engineering_code||'待確認'}</td><td>{money(q.amount)}</td><td>{!reviews.length&&'待 PM／業務共同確認'}{reviews.map((r:any)=><p key={r.id}>{classify[r.classification]} · {r.status==='approved'?'雙方已確認':r.status==='pending'?'待另一方確認':r.status==='superseded'?'舊版留存':'來源變更待重核'}<small>{(r.votes||[]).map((v:any)=>`${v.seat==='pm'?'PM':'業務'} ${nameOf(c.w,v.actor_id)}`).join('、')}</small></p>)}{seats.length>0&&(q as any).review_available!==false&&<ActionForm title="確認此報價" draftId={`quote-review:${p.id}:${q.id}`} busy={c.busy} onSubmit={d=>c.run('quote_review',{quote_id:q.id,...d},{project_id:p.id})}><OpsField title="本次代表職責" name="seat"><select name="seat">{seats.map(([seat,,title])=><option key={seat} value={seat}>{title}</option>)}</select></OpsField><OpsField title="報價分類" name="classification"><select name="classification">{Object.entries(classify).map(([key,title])=><option key={key} value={key}>{title}</option>)}</select></OpsField></ActionForm>}</td><td>{safeUrl(q.source_url)&&<a href={q.source_url} target="_blank" rel="noreferrer">開啟報價</a>}</td></tr>})}</tbody></table>}</div>
}
export function FamilyPanel({c,p}:{c:Ctx;p:Project}){
 const code=p.parent_code||p.code;
 const parent=c.w.projects.find(x=>x.code===code&&x.case_type!=='intake');
 const children=c.w.projects.filter(x=>x.parent_code===code&&x.case_type!=='intake');
 const amounts=children.map(x=>x.contract_amount);
 const complete=amounts.length>0&&amounts.every(x=>typeof x==='number');
 return <div className="detail-page-content operations"><h2>母案 {code}</h2><p>子案各自管理 PM、財務、進度及結案；彙總只計子案，避免加上母案後重複計算。</p>{parent&&<button className="button" onClick={()=>c.go({view:'project',project:parent.id,tab:'family'})}>開啟母案 {parent.code}</button>}<p>子案合約彙總：{complete?money(amounts.reduce((a,b)=>a!+b!,0)):'金額資料未齊備'} · 子案結案須另核對業務及財務條件，不以來源狀態代替</p>{children.length?<table className="data-table"><thead><tr><th>子案</th><th>PM</th><th>進度</th><th>合約金額</th><th>狀態</th></tr></thead><tbody>{children.map(x=><tr key={x.id}><td><button className="text-button" onClick={()=>c.go({view:'project',project:x.id})}>{x.code} {x.name}</button></td><td>{nameOf(c.w,x.pm_id)}</td><td>{progress(x)}%</td><td>{money(x.contract_amount)}</td><td><Badge status={x.status} label={`來源：${x.source_status||'待核對'}`}/></td></tr>)}</tbody></table>:<p>尚無已確認的子案關聯。</p>}</div>
}
