import type {SourceMapping} from './types';

const count=(value?:number)=>typeof value==='number'&&Number.isFinite(value)?value.toLocaleString('zh-TW'):'待確認';
export function SourceMappingSummary({mapping,onReview}:{mapping:SourceMapping;onReview:()=>void}){
 const dailyKnown=Number.isFinite(mapping.daily_imported)&&Number.isFinite(mapping.daily_unmatched);
 const pending=mapping.daily_unmatched>0||(mapping.confirmations_missing_code||0)>0;
 const reasons:[string,number|undefined][]=[['缺少案件關聯',mapping.daily_unmatched_missing_reference],['有關聯但尚未對到案件',mapping.daily_unmatched_unresolved_reference],['關聯指向多個案件',mapping.daily_unmatched_ambiguous_reference]];
 return <section className="operations source-mapping-summary" aria-labelledby="source-mapping-heading"><div className="ops-heading"><h2 id="source-mapping-heading">來源配對結果</h2><span className={`ops-status ${pending?'conflict':''}`}>{pending?'資料已讀取，配對待核對':'查看配對結果'}</span></div><p>來源可讀與案件配對分開記錄；未配對日報仍保留在核對清單，不代表沒有作業。</p><div className="table-scroll"><table className="data-table"><thead><tr><th>項目</th><th>筆數</th></tr></thead><tbody><tr><td>來源日報總數</td><td>{dailyKnown?count(mapping.daily_imported+mapping.daily_unmatched):'待確認'}</td></tr><tr><td>已配對日報</td><td>{count(mapping.daily_imported)}</td></tr><tr><td>待配對日報</td><td>{count(mapping.daily_unmatched)}</td></tr>{reasons.map(([label,value])=><tr key={label}><td>待配對原因：{label}</td><td>{count(value)}</td></tr>)}<tr><td>來源確認單缺少工程確認單編號</td><td>{count(mapping.confirmations_missing_code)}</td></tr></tbody></table></div>{((mapping.daily_missing_date||0)>0||(mapping.daily_conflicting_dates||0)>0||(mapping.daily_missing_department||0)>0)&&<p>另有日期缺漏 {count(mapping.daily_missing_date)} 筆、日期衝突 {count(mapping.daily_conflicting_dates)} 筆、組別缺漏 {count(mapping.daily_missing_department)} 筆；可能與上述紀錄重疊，請勿相加。</p>}{mapping.daily_unmatched>0&&<button className="button" onClick={onReview}>前往日報配對核對</button>}{(mapping.confirmations_missing_code||0)>0&&<p>確認單編號須回原始資料表核對；缺少編號的紀錄不會直接當成正式案件。</p>}</section>;
}
